# NumPy

## Array Basics

In [2]:
import numpy as np

In [3]:
import numpy

### list ==> np array

In [9]:
arr = np.array([1, 2, 3, 4])
arr.dtype

dtype('int64')

In [11]:
print(arr.mean())

2.5


In [13]:
arr_mean = np.mean(arr)
arr_mean

np.float64(2.5)

In [14]:
print(arr_mean)

2.5


In [15]:
num_list = [ 1, 2, 3, 4, 5]

In [16]:
type(num_list)

list

In [19]:
arr = np.array(num_list)

In [20]:
type(arr)

numpy.ndarray

In [21]:
arr.dtype


dtype('int64')

### arange() ==> array

In [22]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [25]:
np.arange(2, 11, 2)   ### start stop step

array([ 2,  4,  6,  8, 10])

In [31]:
list_2d = [
    [1, 2, 3],
    [4, 5, 6]
]

In [32]:
list_2d

[[1, 2, 3], [4, 5, 6]]

In [34]:
list_3d = [
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [11, 2, 3],
        [14, 5, 6]
    ]
]
list_3d

[[[1, 2, 3], [4, 5, 6]], [[11, 2, 3], [14, 5, 6]]]

In [35]:
np.array(list_2d)

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
np.array(list_3d)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[11,  2,  3],
        [14,  5,  6]]])

In [39]:
nums = [ num for num in [1, 2, 3 , 4, 5] ]

In [40]:
nums

[1, 2, 3, 4, 5]

In [41]:
nums2 = [ num**2 for num in [1, 2, 3 , 4, 5] ]
nums2

[1, 4, 9, 16, 25]

In [43]:
nums_if = [ num**2 for num in nums if num % 2 == 0 ]
nums_if

[4, 16]

In [44]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])