# NumPy

## Array Basics

In [51]:
import numpy as np

In [52]:
import numpy

### list ==> np array

In [56]:
np.array((1, 2, 3))

array([1, 2, 3])

In [57]:
arr = np.array([1, 2, 3, 4])
arr.dtype

dtype('int64')

In [58]:
print(arr.mean())

2.5


In [59]:
arr_mean = np.mean(arr)
arr_mean

np.float64(2.5)

In [60]:
print(arr_mean)

2.5


In [68]:
num_list = [ 1, 2.3, 3, 4, 5]

In [69]:
type(num_list)

list

In [70]:
arr = np.array(num_list)

In [71]:
type(arr)

numpy.ndarray

In [72]:
arr.dtype


dtype('float64')

### arange() ==> array

In [74]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [76]:
np.arange(0, 100, 10)   ### start stop step

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [79]:
list_2d = [
    [1, 2, 3], 
    [4, 5, 6]
]

In [80]:
list_2d

[[1, 2, 3], [4, 5, 6]]

In [81]:
list_3d = [
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [11, 2, 3],
        [14, 5, 6]
    ]
]
list_3d

[[[1, 2, 3], [4, 5, 6]], [[11, 2, 3], [14, 5, 6]]]

In [82]:
np.array(list_2d)

array([[1, 2, 3],
       [4, 5, 6]])

In [83]:
np.array(list_3d)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[11,  2,  3],
        [14,  5,  6]]])

In [89]:
nums = [ 1, 2, 3, 4, ] 
[ num**3 for num in nums ]

[1, 8, 27, 64]

In [39]:
nums = [ num for num in [1, 2, 3 , 4, 5] ]

In [40]:
nums

[1, 2, 3, 4, 5]

In [41]:
nums2 = [ num**2 for num in [1, 2, 3 , 4, 5] ]
nums2

[1, 4, 9, 16, 25]

In [43]:
nums_if = [ num**2 for num in nums if num % 2 == 0 ]
nums_if

[4, 16]

In [44]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [48]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [50]:
np.zeros(2, 3)

array([[0., 0., 0.],
       [0., 0., 0.]])