# NumPy Array Operations

1. Basic arithmetic
2. Linear algebra
3. Random numbers

## Arithmetic

You can easily perform array with array arithmetic, or scalar with array arithmetic. Let's see some examples:

In [1]:
# %pip install numpy
import numpy as np
arr = np.arange(0,10)

In [2]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [4]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [5]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [6]:
### division by zero!!! 
### However, unlike Python, you do not receive an error.
### Just replaced with nan
arr / arr

/var/folders/6t/bfp06fh96wn60n_mjtxmbhfm0000gn/T/ipykernel_44124/1831715423.py:4: RuntimeWarning: invalid value encountered in divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [7]:
# Also warning, but not an error instead infinity
1/arr

/var/folders/6t/bfp06fh96wn60n_mjtxmbhfm0000gn/T/ipykernel_44124/1360216608.py:2: RuntimeWarning: divide by zero encountered in divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [8]:
arr**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

### Vectorized Operations 

NumPy does math on whole arrays at once, which much faster than using loops.

In [9]:
arr = np.array([1, 2, 3, 4])
print(arr * 2)              # multiply each element by 2
print(arr + 5)              # add 5 to each element

[2 4 6 8]
[6 7 8 9]


### Broadcasting

NumPy can combine arrays of different shapes by \"stretching\" one to match the other.

In [10]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([10, 20, 30])

print(A + B)

[[11 22 33]
 [14 25 36]]


## Built-in Methods

There are lots of built-in ways to generate Arrays

### arange

Return evenly spaced values within a given interval.

In [11]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

### zeros and ones

Generate arrays of zeros or ones

In [13]:
np.zeros(3)

array([0., 0., 0.])

In [14]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
np.ones(3)

array([1., 1., 1.])

In [16]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### linspace
Return evenly spaced numbers over a specified interval.

In [17]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [18]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

### eye
Creates an identity matrix

In [19]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Universal Array Functions

Numpy comes with many [universal array functions](http://docs.scipy.org/doc/numpy/reference/ufuncs.html), which are essentially just mathematical operations you can use to perform the operation across the array. Let's show some common ones:

In [20]:
#Taking Square Roots
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [21]:
#Calcualting exponential (e^)
np.exp(arr)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [22]:
np.max(arr) #same as arr.max()

np.int64(4)

In [23]:
np.sin(arr)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [24]:
np.log(arr)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

## Reshape
Returns an array containing the same data with a new shape.

In [25]:
arr.reshape(5,5)

ValueError: cannot reshape array of size 4 into shape (5,5)

### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [ ]:
ranarr

In [ ]:
ranarr.max()

In [ ]:
ranarr.argmax()

In [ ]:
ranarr.min()

In [ ]:
ranarr.argmin()

## Broadcasting

Numpy arrays differ from a normal Python list because of their ability to broadcast:

In [ ]:
#Setting a value with index range (Broadcasting)
arr[0:5]=100

#Show
arr

In [ ]:
# Reset array, we'll see why I had to reset in  a moment
arr = np.arange(0,11)

#Show
arr

In [ ]:
#Important notes on Slices
slice_of_arr = arr[0:6]

#Show slice
slice_of_arr

In [ ]:
#Change Slice
slice_of_arr[:]=99

#Show Slice again
slice_of_arr

Now note the changes also occur in our original array!

In [ ]:
arr

Data is not copied, it's a view of the original array! This avoids memory problems!

In [ ]:
#To get a copy, need to be explicit
arr_copy = arr.copy()

arr_copy

### Fancy Indexing

Fancy indexing allows you to select entire rows or columns out of order,to show this, let's quickly build out a numpy array:

In [ ]:
#Set up matrix
arr2d = np.zeros((10,10))

In [ ]:
#Length of array
arr_length = arr2d.shape[1]

In [ ]:
#Set up array

for i in range(arr_length):
    arr2d[i] = i
    
arr2d

Fancy indexing allows the following

In [ ]:
arr2d[[2,4,6,8]]

In [ ]:
#Allows in any order
arr2d[[6,4,2,7]]