# Arrays Basics

NumPy arrays (N-dimensional arrays, or **`ndarray`**) are a powerful extension of Python lists, offering compact storage and fast operations for numerical data in rows and columns.

While NumPy arrays can have any number of dimensions, the most common are:
- **Vectors**: **1-dimensional arrays** with a single axis
- **Matrices**: **2-dimensional arrays** with two axes (rows and columns)

This section covers core concepts for working with NumPy arrays:
- Array data structure
- Creating arrays
- Indexing and slicing
- Array attributes (ndim, dtype, shape) and functions like reshape()

## NumPy Data Structure

The primary data structure in NumPy is the N-dimensional array, or **`ndarray`**. NumPy's arrays are a list of lists in Python, but are more compact than Python lists. In essence, a Python list is an array of pointers to heterogeneous Python objects, while a NumPy array is an array of **uniform** values of the same type (e.g., all integers, all floats) and array elements are stored in one continuous block of memory, similar to how arrays work in C ({numref}`c-vs-python-list`). Python lists are more flexible, but Numpy arrays are smaller in file size, and access in reading and writing items is much faster {cite}`Martelli_2009`.

<!-- , at least 4 bytes per pointer plus 16 bytes for even the smallest Python object (4 for type pointer, 4 for reference count, 4 for value -- and the memory allocators rounds up to 16).  -->

<!-- (4 bytes each for single-precision numbers and 8 bytes double-precision).  -->



```{figure} ../../images/c-vs-python-list.png
---
width: 350px
name: c-vs-python-list
alt: c-vs-python-list
align: center
---
Difference between NumPy array (C) and Python lists {cite}`Vanderplas_2022`
```

In short, NumPy's primary data structure is the ndarray (N-dimensional array), which is a **homogeneous**, **multidimensional** array of fixed-size items. This means all elements within an ndarray must be of the same data type (note: To store heterogeneous data, NumPy uses structured arrays). While Python defines only one type of a particular data class (there is only one integer type, one floating-point type, etc.), there are 24 new fundamental Python types to describe different types of scalars in NumPy. 


```{figure} ../../images/np-array-data-types.png
---
width: 450px
name: np-array-data-types
alt: np-array-data-types
align: center
---
Hierarchy of type objects representing the array data types ([Numpy Scalars](https://docs.scipy.org/doc/numpy-1.14.1/reference/arrays.scalars.html))
```

In NumPy, the terms scalar, vector, and matrix refer to specific dimensions of these arrays.

```{figure} ../../images/scalar-vector-matrix-tensor.png
---
width: 400px
name: scalar-vector-matrix-tensor
alt: scalar-vector-matrix-tensor
align: center
---
Scalar, Vector, Mmatrix, and Tensor ([Harshit Tyagi](https://medium.com/data-science/introduction-to-vectors-and-matrices-using-python-for-data-science-e836e014eb12))
```



<!-- <img src="../images/c-vs-python-list.png"
alt="c-vs-python-list"
style = "width: 350px"> 
name= "c-vs-python-list"
caption = Difference between C and Python lists {cite}`Vanderplas_2022`
-->

## Using Numpy
### Installing NumPy

To install NumPy, you would:
1. Go to the command line
2. Navigate to your project directory (dsm)
3. activate the virtual environment 
4. Issue the `pip install [package]` syntax to install: 

```python
pip install numpy
```
<!-- <code>
pip install numpy
</code> -->

You should see the installation happens like:

```python
(.venv) tychen✪macː~/workspace/dsm$ pip install numpy
Collecting numpy
Downloading numpy-2.3.3-cp312-cp312-macosx_14_0_arm64.whl.metadata (62 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.1/62.1 kB 1.3 MB/s eta 0:00:00
Downloading numpy-2.3.3-cp312-cp312-macosx_14_0_arm64.whl (5.1 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.1/5.1 MB 4.1 MB/s eta 0:00:00
Installing collected packages: numpy
Successfully installed numpy-2.3.3
```


```{note}
Alternatively, in a Jupyter notebook, you may issue `%pip install` [package] in a code cell to install packages just like like `pip install` [package] in the command line. You will also see people use `!pip install` as well. `!pip` runs pip as a shell command, while `%pip` is a Jupyter magic function that works in the current running notebook kernel, which allows you to customize your notebooks. 

Don't forget to comment out your `pip` commands in the cells, or it will keep running every time you run the cells.
```

### `import` NumPy

Once you've installed NumPy, you can import it as a library and give it an alias:

In [2]:
import numpy as np

After you import a module/library, you use the **dot notation** to access the objects (methods/functions and attributes/properties) inside the module/library. 

```
import numpy as np

np.array([1, 2, 3])
```
Here, `np` is an **alias** for numpy, and the dot notation gives us access to the contained objects, such as `array()` in this case.


Just as Python lists do, NumPy provides many built-in functions and capabilities. For example:

```
arr = np.array([1, 2, 3, 4, 5])     ### creating array
print(np.mean(arr))                 # mean
print(np.std(arr))                  # standard deviation

```

## Creating NumPy Arrays

### From a Python List/Tuple

You can create an array by directly **casting** a list to an array. Let us create a list first:

In [32]:
num_list = [1,2,3, 4, 5]
print(num_list)
print(type(num_list))

[1, 2, 3, 4, 5]
<class 'list'>


Now let's cast the list into a numpy array using numpy's `array()` method to create a **1-D** array.

In [33]:
### before using numpy, import
### we usually import packages at the very beginning of a notebook

import numpy as np

In [34]:
arr = np.array(num_list)       ### casting a list to a numpy array
arr

### now you will see a numpy array, which is array([ ele, ele, ele ]) from the list [1, 2, 3, 4, 5]

array([1, 2, 3, 4, 5])

In [35]:
### data type is different from list too: numpy.ndarray 

type(arr)                   

numpy.ndarray

#### `dtype`

The **dtype** keyword allows you to explicitly set the data type of the resulting array:

In [37]:
np.array([1, 2, 3, 4], dtype=np.float32)

array([1., 2., 3., 4.], dtype=float32)

### Using arange() Function

**`numpy.arange()`** is a NumPy function used to create arrays with evenly spaced values with a specified interval. It is similar to Python's built-in `range()` function, but returns a NumPy `ndarray` instead of a `range` object, which is more efficient for numerical operations.


In [36]:
np.arange(5)

array([0, 1, 2, 3, 4])

Using the range parameters: start, stop exclusive, stop:

In [25]:
np.arange(2, 11, 2)

array([ 2,  4,  6,  8, 10])

We can also place a Python **nested** list (list of lists) directly into the np.array function to create a NumPy array (note that this is a **2-D** array):

In [26]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


An example of Python **3-D** list, which is a list of lists: 

In [27]:
list_of_list = [
    [
        [1, 2, 3, 4], 
        [2, 2, 3, 4], 
        [3, 2, 3, 4]
    ], 
    [
        [4, 2, 3, 4], 
        [5, 2, 3, 4], 
        [6, 2, 3, 4]
    ]
]
list_of_list

[[[1, 2, 3, 4], [2, 2, 3, 4], [3, 2, 3, 4]],
 [[4, 2, 3, 4], [5, 2, 3, 4], [6, 2, 3, 4]]]

Compare the result of the evaluation of the Python list above with the NumPy array created from the list:

In [28]:
np.array(list_of_list)

array([[[1, 2, 3, 4],
        [2, 2, 3, 4],
        [3, 2, 3, 4]],

       [[4, 2, 3, 4],
        [5, 2, 3, 4],
        [6, 2, 3, 4]]])

### Using List Comprehension

Note that the syntax of list comprehension is an alternative to **for loops**. Instead of initializing an empty list variable and running a for loop to append elements, list comprehension is more concise. The syntax for list comprehension is:

```
[expression for item in iterable]
```

In [29]:
np.array([i**2 for i in range(10)])

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [38]:
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

Or, list comprension with a condition as **filter**:
```
[expression for item in iterable if condition]
```


In [40]:
evens = [x for x in range(10) if x % 2 == 0]
evens

[0, 2, 4, 6, 8]

### Using Other `np` Functions: 

1. zeros( ):
  `np.zeros(shape, dtype=float, order='C')`
2. ones( ): `np.ones(shape, dtype=float, order='C')`
3. full( ): create an array filled with a certain value 
  
    `np.full(shape, fill_value, dtype=None, order='C')`
4. linspace( ): `np.linspace(start, stop, num=50 default, endpoint=True, retstep=False, dtype=None, axis=0)`
5. eye( ): `np.eye(N, M=None, k=0, dtype=float, order='C')`

#### zeros(), ones(), and full()

These functions initialize arrays of a specified **shape** filled with zeros, ones, or a constant value, respectively. The syntax for numpy.ones(), zeros(), and full() functions is:

<code>numpy.ones(shape, dtype=None, order='C', *, like=None)</code>

Note that we pass the shape argument using a list or a tuple or list. 

In [87]:
np.zeros(5, dtype=int)

array([0, 0, 0, 0, 0])

In [88]:
np.zeros((3, 4))     ### passing shape parameter with a tuple   
                     ### by default, the dtype is float64

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [89]:
arr_ones = np.ones(3)   ### vector array of 1's 
arr_ones                ### type float64 by default

array([1., 1., 1.])

In [90]:
arr_ones.dtype

dtype('float64')

In [91]:
arr_ints = np.ones([2,3], int)     ### specify dtype to int
print(arr_ints)
print(type(arr_ints))
print(arr_ints.dtype)

[[1 1 1]
 [1 1 1]]
<class 'numpy.ndarray'>
int64


In [92]:
np.full( (5) , 5)

array([5, 5, 5, 5, 5])

In [93]:
np.full((2, 3), 5)      ### fill the shape (2x3) with 5

array([[5, 5, 5],
       [5, 5, 5]])

#### linspace()

`linspace( )` stands for linear space. linspace returns evenly spaced numbers over a specified interval. Note that the **stop** parameter is <span style="color: darkred">**inclusive**</span>. 

In [103]:
### Create an array of five values evenly spaced between 0 and 1

np.linspace(0, 10, 5, dtype=int)

array([ 0,  2,  5,  7, 10])

In [115]:
arr = np.linspace(0, 26, 27, dtype=int)
print(arr)
print("shape    :", arr.shape)
print("dimension: ", arr.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]
shape    : (27,)
dimension:  1


#### eye()
Creates an identity matrix:

In [118]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## The numpy.random module 

(These functions are considered "[legacy random generation](https://numpy.org/doc/stable/reference/random/legacy.html#legacy)" and are for simple random data. 

The numpy.random module in NumPy provides tools for generating pseudo-random numbers and sampling from various probability distributions. Some functions in the numpy.random module are commonly used:
- **np.random.rand()**: returns random floating-point numbers (**uniform distribution** over the interval [0, 1))
- **np.random.randn()**: returns random floating-point numbers (**standard normal distribution** with mean of 0 and standard deviation of 1)
- **np.random.randint()**: returns random integers from a specified range
- **np.rand
- (note that np.random.random is the same as random.rand(), except random.random() takes the shape argument as a single tuple; e.g., see [stackoverflow](https://stackoverflow.com/questions/47231852/np-random-rand-vs-np-random-random))

As a summary, here's a comparison table of the commonly used methods in the numpy random module:

| Function  | Distribution  | Typical Use     | Note |
| --------- | ------------- | --------------- |- |
| `rand`    | Uniform [0,1) | Random decimals | uniform decimals |
| `random`  | Uniform [0,1) | Same as rand    | uniform decimals |
| `randn`   | Normal (0,1)  | Stats, ML       | bell curve; mean and SD control |
| `normal`  | Normal (μ, σ) | Simulations     | bell curve; no mean and SD control  |
| `randint` | Integers      | Dice, indexing  | whole numbers |

Simple examples of the random numbers are:

### random.rand( )

In [215]:
### rand: one number

np.random.rand()

0.16121393664166028

In [216]:
### rand: 1D array
# from numpy import random     ### different import syntax

np.random.rand(3)

array([0.93068871, 0.21631727, 0.59506622])

In [217]:
### rand: 2D

random.rand(2, 3)

array([[0.26261918, 0.76146849, 0.18926142],
       [0.42736538, 0.79374906, 0.92329574]])

### random.random()

In [221]:
np.random.random()

0.39189636217351265

In [222]:
np.random.random(3)

array([0.96203291, 0.06667942, 0.78692241])

In [223]:
# create a 3x3 array of uniformly distributed
# pseudorandom values between 0 and 1

np.random.random((2, 3))

array([[0.45618239, 0.87022885, 0.38743912],
       [0.03836349, 0.97890136, 0.30069517]])

### random.randn( )

In [224]:
### randn: 1 number, normal distribution
np.random.randn()

1.677059279527663

In [230]:
### randn: 1D array
np.random.randn(3)

array([ 0.90424236, -0.63281355, -1.04947358])

In [231]:
### randn: 2D array
np.random.randn(2, 3)

array([[-1.02428275,  0.7960977 , -1.3249619 ],
       [ 0.83060152, -0.96321582, -1.18366418]])

In [278]:
### randn: 2D array
np.random.randn(0, 5, 2, 3)

array([], shape=(0, 5, 2, 3), dtype=float64)

### random.normal()

`np.random.normal(loc=0.0, scale=1.0, size=None)`

**loc = location of mean**

In [280]:
np.random.normal()

0.02075651737049734

In [281]:
np.random.normal(3)

3.812941939429069

In [282]:
# create a 3x3 array of normally distributed pseudorandom
# values with mean 0 and standard deviation 1

np.random.normal(0, 1, (2, 3))

array([[-1.02723297,  0.37557688,  0.73677647],
       [-0.46197391, -0.01608159,  1.15505978]])

### random.randint( )

In [283]:
### randint: 1 number

print(np.random.randint(10))   ### range between 0 and 10 exclusive
print(np.random.randint(5, 10))   ### range between 5 and 10 exclusive

8
9


In [284]:
### randin: 1D array (with size parameter)

np.random.randint( 0, 10 )   ### 0 to 10 exclusie

3

In [285]:
# create a 3x3 array of pseudorandom integers in the interval [0, 10)

np.random.randint(0, 10, (3, 3))

array([[8, 7, 9],
       [7, 8, 3],
       [7, 8, 5]])

### choice( ) and size

In [286]:
### the choice function

np.random.choice([3, 5, 7, 9], size = 2)


array([9, 5])

In [287]:
### the size parameter to generate N-D arrays

np.random.choice([3, 5, 7, 9], size=(3, 5))


array([[9, 3, 9, 7, 3],
       [7, 5, 7, 7, 5],
       [3, 9, 7, 5, 3]])

## Indexing and Selection

Just like Python lists, square brackets [] are used for selecting the elements or groups of elements from an array:
1. accessing individual elements of a list (**indexing**).
2. selecting sub-sequences (**slicing** with parameters: start, stop exclusive, and step). Note that slicing returns a numpy array.
3. **negative** indexing: begins with -1 from the end of the sequence.

In [288]:
import numpy as np

In [289]:
### creating sample array
arr = np.arange(0,10)

In [290]:
### show the array
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [291]:
### indexing 
arr[1]

np.int64(1)

In [292]:
arr[0:3]

array([0, 1, 2])

In [293]:
arr[0:5:2]

array([0, 2, 4])

In [294]:
arr[-1]

np.int64(9)

In [295]:
### start is -3, and stop is -1 exclusive
arr[-3:-1]

array([7, 8])

### Indexing/Slicing 2-D Aarrays (Matrices)

To access a 2-D array (matrices), use the syntax `array[row_index, column_index]`. The general format is **arr[row][col]** or **arr[row, col]**. 

In [296]:
### creating a 2-d array

arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [297]:
### 0-based indexing; 1st row
arr_2d[0]

array([ 5, 10, 15])

In [298]:
### 0-based indexing
arr_2d[1, 2]

np.int64(30)

In [299]:
### 2D array slicing
### shape (2,2) from top right corner

arr_2d[:2, 1:]

array([[10, 15],
       [25, 30]])

### One More Example: 2-D Array (Matrix)

In [304]:

arr_2d = np.array(
    (
        [5,10,15],
        [20,25,30],
        [35,40,45]
    )
)

#Show
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [305]:
### indexing row
arr_2d[1]

array([20, 25, 30])

In [306]:
### Format is arr_2d[row][col] or arr_2d[row,col]

### Getting individual element value
arr_2d[1][0]     ### 2nd row, 1st column

np.int64(20)

In [307]:
### getting individual element value
arr_2d[1,0]

np.int64(20)

In [308]:
# 2D array slicing

### shape (2,2) from top right corner
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [309]:
### shape bottom row
arr_2d[2]

array([35, 40, 45])

In [310]:
### also shape bottom row with colon

arr_2d[2,:]

array([35, 40, 45])

## Array Attributes

Commonly used NumPy array attributes include:

- `ndim`: number of dimensions (rank)
- `shape`: tuple of lengths per axis (assignable to reshape if sizes match)
- `dtype`: data type of elements (e.g., float64, int32, complex128)

### dtype

The dtype property in NumPy is an attribute of a NumPy array (ndarray) that represents the data type of the elements contained within the array.

You can get the data type of the object in the array:

In [311]:
arr = np.arange(25)
arr.dtype

dtype('int64')

In [312]:
arr_string = np.array(['apple', 'banana', 'cherry'])

print(arr_string.dtype)
### U means UTF8, 6 is the longest string

<U6


In [313]:
arr = np.array([1, 2, 3, 4], dtype='i4')

print(arr)
print(arr.dtype)

[1 2 3 4]
int32


### ndim
The ndim attribute represents the number of dimensions (or axes) of the array.

In [314]:
arr.ndim

1

In [315]:
arr_25 = np.arange(25)
arr_55 = arr_25.reshape(5, 5)
arr_55.ndim

2

### shape

The shape attribute **returns a tuple** of integers at every index tells about the number of elements the corresponding dimension has.

In [316]:
arr_2d = np.array([ [1, 2, 3], [4, 5, 6] ])
arr_2d.shape

(2, 3)

In [317]:
### create a 1-D array

arr_vec = np.arange(1, 10, 2)
arr_vec

array([1, 3, 5, 7, 9])

In [318]:
### a vector (an ordered list or an array of numbers, often 
### representing multiple related variables or observations)
arr_vec.shape

(5,)

In [319]:
### np.array([list comprehension])
arr_25 = np.array([ num for num in range(25)])
arr_25

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [320]:
arr_25.shape

(25,)

### The reshape() Function 
The reshape() function changes the shape of a NumPy array without altering its underlying data. It **returns a new array** (or a view of the original array if possible) with the specified new shape.

In [116]:
arr = np.linspace(0, 26, 27, dtype=int)
print(arr)
arr.reshape(3, 9)
print(arr)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [321]:
### arr
arr = np.array(
    [num for num in range(16)]
)

arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [328]:
### reshape
arr = arr.reshape(4, 4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [323]:
arr.reshape(2, 8)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [324]:
### this will not work

# arr.reshape(5,5)

In [325]:
arr_25 = np.arange(25)
arr_25.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [326]:
arr_25.reshape(5, 5).shape

(5, 5)

In [327]:
### reshape does not change the object

arr_25

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [69]:
arr_25.shape

(25,)