In [1]:
# %pip install nbclassic

In [2]:
path_data='./data'
import os
os.listdir(path_data)

['roulette_wheel.csv',
 'birds.csv',
 'bta.csv',
 'all-lprs.csv.gz',
 'hodgkins.csv',
 'observed_outcomes.csv',
 'family_heights.csv',
 'nba2013.csv',
 'galton_subset.csv',
 'san_francisco_2019.csv',
 'kaiser_ethnicity_everyone.csv',
 'ckd.csv',
 'little_women.csv',
 'cones.csv',
 'station.csv',
 'baby.csv',
 'shotput.csv',
 'hybrid.csv',
 'grades_and_piazza.csv',
 'hybrid_reg.csv',
 'educ_inc.csv',
 'married_couples.csv',
 'everyone_raw.csv',
 'potential_outcomes.csv',
 'airline_ontime.csv',
 'football.csv',
 'usa_ca_2014.csv',
 'children_raw.csv',
 'banknote.csv',
 'sat2014.csv',
 'IV.csv',
 'scores_by_section.csv',
 'trip.csv',
 'minard.csv',
 'income_small.csv',
 'sons_heights.csv',
 'chinook.db',
 'dugongs.csv',
 'breast-cancer.csv',
 'actors.csv',
 'couples.csv',
 'nba_salaries.csv',
 'nc-est2014-agesex-res.csv',
 'usa_ca_2019.csv',
 'wine.csv',
 'heights.csv',
 'nc-est2015-agesex-res.csv',
 'house.csv',
 'kaiser_ethnicity_children.csv',
 'little_women.txt',
 'unfair_flips.csv',


In [3]:
import numpy as np

In [4]:
# lst = [True, False, False]
# sum(lst)

In [5]:
np.arange(1, 5)

array([1, 2, 3, 4])

In [6]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [7]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [8]:
pow(2, 3)

8

In [9]:
# in Python, without numpy, you use math.pow()
import math
math.pow(2, 3)

8.0

In [10]:
from datascience import *

ModuleNotFoundError: No module named 'datascience'

In [ ]:
# Table.read_table("data.csv").show(5)
flights = Table.read_table('./data.csv')
flights.show(3)

In [ ]:
dates = flights.column('Date')
dates

In [ ]:
dates.item(0)

In [ ]:
destination = flights.column(2)
destination

In [ ]:
destination.item(0)

In [ ]:
destination[0]

In [ ]:
import numpy as np
np.mean(flights.column('Delay'))

In [ ]:
np.max(flights.column('Delay'))

In [ ]:
delay = flights.column('Delay')
delay.max()

In [ ]:
np.max(delay)

In [ ]:
test = flights.drop('Delay')[0]

In [ ]:
test


In [ ]:
data='./data'

In [ ]:
Table.read_table('./data/nba_salaries.csv')


In [ ]:
nba = Table.read_table('./data/nba_salaries.csv')
nba.where('POSITION', 'PG')

In [ ]:
import numpy as np

In [ ]:
from datascience import *
make_array(1, 2, 3 ,4 ,5)

In [ ]:
arr = make_array(1,2,3,4,5)
type(arr)

In [ ]:
nba = './data/nba_salaries.csv'

In [ ]:
nba = Table.read_table(nba)

In [ ]:
nba

In [ ]:

nba.where("'15-'16 SALARY", are.equal_to(8))

In [ ]:
from datascience import *


In [ ]:
odd_array = make_array(1, 3, 5, 7.00010001)
# odd_array

In [ ]:
import numpy as np
even_array = np.arange(2, 10, 2)
even_array

In [ ]:
odd_array + even_array

In [ ]:
odd_array[0]

In [ ]:
odd_array[3]

In [ ]:
odd_array.item(3)

In [ ]:
lst = [1, 3, 5]

In [ ]:
type(lst)

In [ ]:
type(np.arange(10))

In [ ]:
teams = Table().with_columns(
    'name', make_array('Celtics', 'Lakers', 'Nets', 'Pistons', 'Rockets') ,
    'division', ['Atlantic', 'Pacific', 'Atlantic', 'Central', 'Southwest'],
    'conference', ('Eastern', 'Western', 'Eastern' ,'Eastern', 'Western'),
    'arena', np.array([18642, 18997, 17732, 20491, 18055])
)
teams

In [ ]:
players = Table().with_columns(
 "name", ["Stephen Curry", "Dwight Howard", "Zion Williamson", 'TY Chen', 'TY Chen', 'TY Chen'],
    "2019", [37457154, 5337000, 0, 200, 300, 400],
    "2020", [40231758, 1620564, 9757440, 111, 222, 1],
    "19team", ["Warriors", "Wizards", "No Team", 'Nets', 'Nets', 'Lakers'],
    "20team", ["Warriors", "Lakers", "Pelicans", 'Nets', 'Nets', 'Lakers']
)
players

In [ ]:
import random
# random.sample(players.column('name'), 5)
random.sample(list(players.column('2019')), 3)

In [ ]:
players.where('2019', 200)

In [ ]:
teams.sort('arena', descending=False).column('name').item(0)

In [ ]:
teams.where('conference', are.equal_to('Eastern')).group('division')

In [ ]:
# teams.join('name', players, '20team').select('division', '2020').group('division', sum)

In [ ]:
# %magic

In [ ]:
# %hist

In [ ]:
# %edit

In [ ]:
# %env

In [ ]:
# %clear

In [ ]:
# %dirs

In [ ]:
np.array( ( 1, 2, 3 ) )

In [ ]:
make_array(1, 2, 3 ) 

In [ ]:
# '5' + 5

In [ ]:
marbles = Table.read_table('marbles.csv')

In [ ]:
marbles.show(3)

In [ ]:
marbles.where("size", 'large')

In [ ]:
marbles

In [ ]:
# 4 + 'a'

In [ ]:
teams

In [ ]:
teams.rows

In [ ]:
teams.columns

In [ ]:
teams.labels

In [ ]:
# abc

In [ ]:
type(make_array(1, 2, 3))

In [ ]:
type(np.array([1, 2, 3]))

In [ ]:
die = Table().with_column(
    'Face', np.arange(1, 7, 1)
                    )
die

In [ ]:
actors = Table.read_table('data/actors.csv')
actors

In [ ]:
actors.sample(5, with_replacement=False).column('Actor')

In [ ]:
import random
np.random.choice(actors.column('Actor'), 5, replace=False)

In [ ]:
actors.select('Actor').sample(5)

In [ ]:
actors.where('Number of Movies', 45)

In [ ]:
# '5' + 5

In [ ]:
# 4 + 'a'

In [ ]:
# import os
# os.listdir('data')

In [ ]:
flowers = Table().with_columns(
    'Number of petals', [8, 34, 5],
    'Name', ['lotus', 'sunflower', 'rose'],
    'Weight', [10, 5, 6]
)

flowers

In [ ]:
flowers.column('Weight')[1]

In [ ]:
##### function not available in the book ###
##### we will learn about functions later

import ssl

context = ssl._create_unverified_context()

def read_url(url):
    from urllib.request import urlopen
    import re
    return re.sub('\\s+', ' ', urlopen(url, context = context).read().decode())
    
# from urllib.request import urlopen 
# import re
# def read_url(url):            ##### not working
#     return re.sub('\\s+', ' ', urlopen(url).read().decode())


In [ ]:
###### Read two books, fast! (CH1.3)

huck_finn_url = 'https://www.introdsm.org/data/huck_finn.txt'
huck_finn_text = read_url(huck_finn_url)
huck_finn_chapters = huck_finn_text.split('CHAPTER ')[44:]

little_women_url = 'https://www.introdsm.org/data/little_women.txt'
little_women_text = read_url(little_women_url)
little_women_chapters = little_women_text.split('CHAPTER ')[1:]

In [ ]:
# In each chapter, count the number of all characters;
# call this the "length" of the chapter.
# Also count the number of periods.

chars_periods_huck_finn = Table().with_columns([
        'Huck Finn Chapter Length', [len(s) for s in huck_finn_chapters],
        'Number of Periods', np.char.count(huck_finn_chapters, '.')
    ])
chars_periods_little_women = Table().with_columns([
        'Little Women Chapter Length', [len(s) for s in little_women_chapters],
        'Number of Periods', np.char.count(little_women_chapters, '.')
    ])

In [ ]:
chars_periods_huck_finn

In [ ]:
chars_periods_little_women

In [ ]:
chars_periods_huck_finn.join('Number of Periods', chars_periods_little_women, 'Number of Periods')
chars_periods_huck_finn.join('Number of Periods', chars_periods_little_women)
# chars_periods_huck_finn.join('Huck Finn Chapter Length', chars_periods_little_women, 'Little Women Chapter Length')

In [ ]:
for i in range(1, 10, 3):
    print(i)
    print(type(i))

In [ ]:
for i in np.arange(1, 10, 3):
    print(i)
    print(type(i))

In [ ]:
num_repetition = 10
heads = make_array()

for i in np.arange(num_repetition):     ### with np.arange
    heads = np.append(heads, i)
    print(i, end=" ")

In [ ]:
num_repetition = 10
heads = make_array()

for i in range(num_repetition):
    heads = np.append(heads, i)
    print(i, end=" ")

In [ ]:
die = make_array(1, 2, 3, 4, 5, 6)
# die = make_array(np.arange(1, 7))
def roll():
    return np.random.choice(die)
print(roll())
# die

# np.random.choice(die, 1)

In [ ]:
from datascience import * 

arr = [1, 2, 3, 4, 5]

In [ ]:
percentile(25, arr)

In [ ]:
import numpy as np
s = [1, 5, 7, 3, 9]
s = np.sort(s)
s

In [ ]:
percentile(10, s)

In [ ]:
percentile(39, s)

In [ ]:
percentile(40, s)

In [ ]:
percentile(50, s)

In practical terms, suppose there are $n$ elements in the collection. To find the $p$th percentile:
- Sort the collection in increasing order.
- Find p% of n: $(p/100) \times n$. Call that $k$.
- If $k$ is an integer, take the $k$th element of the sorted collection.
- If $k$ is not an integer, round it up to the next integer, and take that element of the sorted collection.

In [ ]:
import numpy as np
from datascience import *
nums = [1, 2, 3, 4, 5, 6, 7 ]
print(np.average(nums))
# max(s)

In [ ]:
percentile(50, nums)

In [ ]:
nums[int(np.floor(50/100 * len(nums))) ]

In [ ]:
# from scipy import stats
from datascience import *
import pandas as pd
path_data = './data/'
nba13 = Table.read_table('./data/nba2013.csv')
nba_df = nba13.to_df()
nba_df.describe()       ##### works

In [ ]:
data = pd.read_csv('./data/nba2013.csv')

In [ ]:
data.describe()

In [ ]:
type(data)

In [ ]:
data

In [ ]:
# sample(data, 5)
data.sample(5)

In [ ]:
from datascience import *
die_arr = make_array(1, 2, 3, 4, 5, 6)
die_tbl = Table().with_column('num', die_arr)

In [ ]:
die_arr

In [ ]:
die_tbl

In [ ]:
die_tbl.sample()

In [ ]:
die_tbl.sample(1)

In [ ]:
die_tbl.sample(1)[0]

In [ ]:
die_tbl.sample(1)[0][0]

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

rolls = make_array()
for i in range(10000):
    rolls = np.append(rolls, die_tbl.sample(1)[0][0])

tbl = Table().with_column('roll', rolls)
# tbl.hist()
# tbl.hist(bins=np.arange(1, 8, 1))
tbl.hist(bins=np.arange(0.5, 7, 1))

In [ ]:
print(len(rolls))
plt.hist(rolls, bins=np.arange(0.5, 6.5, 1))

In [ ]:
rolls_avg = make_array()
rolls = make_array()
for i in range(1000):
    for j in range(100):
        rolls_avg = np.mean(np.append(rolls_avg, die_tbl.sample(1)[0][0]))
    
    rolls = np.append(rolls, rolls_avg)

# rolls.hist()    ### Tble.hist() requires a table
tbl = Table().with_column('roll', rolls)
tbl
# tbl.hist()
# tbl.hist(bins=np.arange(1, 7, 1))
tbl.hist(bins=np.arange(0, 8, .01))
# plt.hist(rolls)

In [ ]:
# len(rolls)
rolls_avg

In [ ]:
tbl.to_df().describe()

In [ ]:
tbl

In [ ]:
np.mean(tbl[0])

In [ ]:
np.mean([1, 2, 3, 4, 5, 6])

In [ ]:
dice.sample(1)[0]

In [ ]:
dice.sample(1)[0][0]

In [ ]:
dice.sample(1)[0][0]

In [ ]:

import random

die_py = [1, 2, 3, 4, 5, 6]
print(random.sample(die_py, k=1))
print(type(random.sample(die_py, k=1)))
print(random.sample(die_py, k=1)[0])

die_py_lst = []
for i in range(10000):
    random.sample(die_py, k=1)


In [ ]:
import numpy as np
samplesize = [2, 3]
np.random.normal(0, 1, samplesize)

In [ ]:
from datascience import *
import numpy as np
%matplotlib inline

coin = make_array('Heads', 'Tails')                 ### create the coin array 
def one_simulated_value():                          ### create the function
    outcomes = np.random.choice(coin, 100)          ### one simulation is heads count of 100 tosses
    return np.count_nonzero(outcomes == 'Heads')    ### only return the number of heads

one_simulated_value()                               ### test if the simulation works

num_repetitions = 20000                             ### number of repetitions
heads = make_array()                                ### empty array

for i in np.arange(num_repetitions):                ### loop through repetitions
    new_value = one_simulated_value() 
    heads = np.append(heads, new_value)             ### np.append(ARR, VAL)

len(heads)                                          ### check the length of the heads array

simulation_results = Table().with_columns(          ### create a table of the results
    'Repetiion', np.arange(1, num_repetitions + 1), ### this is the count
    'Number of Heads', heads                        ### 
)

min_sim = min(simulation_results['Number of Heads']) - .5
max_sim = max(simulation_results['Number of Heads']) + 1

simulation_results.hist('Number of Heads', bins = np.arange(min_sim , max_sim, 1))  
min_sim, max_sim

In [ ]:
tbl = Table().with_columns(
    'a', [1, 2, 3, 4, 5],
    'b', [6, 7, 8, 9, 10]
)

In [ ]:
tbl

In [ ]:
tbl.sample(5)

In [ ]:
names = ['Kaden Browne',
'Tsangyao Chen',
'Colin Craig',
'Tony Dicampo',
'Joshua England',
'Haley Garrison',
'Henry Gnann',
'Brandon Green',
'Terrell Heredia',
'Christopher Holland',
'Nicholas Huellinghoff',
'Quinn Johnson',
'Christopher Kenny',
'Justin Kincaid',
'Maxwell Klein',
'Jamila Latimore',
'Nina Martinez-Alvarez',
'Jacob Meyers',
'Anshuman Mishra',
'Avery Mitchell',
'Hawa Mohammadi',
'Clair Parsons',
'Manav Raja Vinotha',
'Connor Shorts',
'Harry Signaigo',
'Mohammad Fuzail Ahamed Syed',
'Devin Tyler',
'Ryan Veatch']

In [ ]:
import numpy as np
print(np.random.choice(names, 3))

In [ ]:
arr = np.array([1, 2, 3])
arr

In [ ]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print(arr)

In [ ]:
arr = np.array([1, 2, 3, 4])
print(arr * 2)              # multiply each element by 2
print(arr + 5)              # add 5 to each element

In [ ]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([10, 20, 30])

print(A + B)

In [ ]:
A.dtype

In [ ]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [11]:
import numpy as np

In [13]:
arr = np.array((1, 2, 3, 4, 5 ))

In [14]:
arr


array([1, 2, 3, 4, 5])

In [15]:
type(arr)

numpy.ndarray

In [20]:
np.array([ num for num in range(10)])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
arr = np.arange(1, 15, 3)

In [30]:
np.zeros([5, 5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [34]:
np.linspace(1, 10, 50)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [35]:
from numpy import random

In [56]:
arr = random.rand(3, 5)

In [64]:
arr[2, 3] = 100000

TypeError: 'int' object does not support item assignment

In [62]:
arr

array([[7.50102730e-01, 3.25319651e-01, 4.27257245e-01, 9.09503478e-01,
        9.32239333e-01],
       [9.58288161e-01, 1.06279867e-01, 5.07680380e-01, 6.76620819e-01,
        7.39897070e-01],
       [8.48166724e-01, 4.97540726e-01, 6.61073702e-01, 1.00000000e+05,
        7.35573045e-01]])

In [54]:
random.randint(100, size=5)

array([78, 93, 63,  2, 91])

In [66]:
arr = np.arange(0, 10)

In [67]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [73]:
print(arr[ 1 : 5 : 2 ])

[1 3]


In [75]:
arr = np.arange(16)

In [76]:
arr.reshape(4, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [11]:
%%script echo ""

print("This will not run")
x = 5


don't run
