# NumPy Arrays Basics

NumPy arrays (n-dimensional array, or `ndarray`) NumPy is like a super-powered list that can store numbers in rows and columns. NumPy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays has only one axis, and matrices are 2-d arrays with two axes: (rows, columns).

 Mastering arrays, vectorization, and broadcasting will give you a strong foundation for data science and beyond.

## Creating NumPy Arrays
You can create an array by directly casting a list to an array. Let us create some lists first:

In [1]:
nums_list = [1,2,3]
nums_list

[1, 2, 3]

In [2]:
type(nums_list)

list

Now let's cast the list into a numpy array using numpy's `array()` method.

In [4]:
### before using numpy, import
import numpy as np

In [6]:
arr = np.array(nums_list)       ### casting a list to a numpy array
arr

### now you will see a numpy array, which is different from the list [1, 2, 3]

array([1, 2, 3])

In [10]:
### data type is different from list too: numpy.ndarray 

type(arr)                   

numpy.ndarray

Now let's cast a Python list of lists into NumPy array:

In [11]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
list_of_list = [[1,2,3],[4,5,6],[7,8,9]]
list_of_list

Compare the result of evaluation of the Python list above with the NumPy array:

In [ ]:
np.array(list_of_list)

## NumPy Indexing and Selection

Just like Python lists, there are ways for selecting the elements or groups of elements from an array.

In [ ]:
import numpy as np

In [ ]:
### creating sample array
arr = np.arange(0,11)

In [ ]:
### show the array
arr

## Shape

Shape is an attribute that arrays have (not a method):

In [ ]:
# Vector
arr.shape

In [ ]:
# Notice the two sets of brackets
arr.reshape(1,25)

In [ ]:
arr.reshape(1,25).shape

In [ ]:
arr.reshape(25,1)

In [ ]:
arr.reshape(25,1).shape

### dtype

You can also grab the data type of the object in the array:

In [ ]:
arr.dtype

## Bracket Indexing and Selection
The simplest way to pick one or some elements of an array looks very similar to python lists:

In [ ]:
#Get a value at an index
arr[8]

In [ ]:
#Get values in a range
arr[1:5]

In [ ]:
#Get values in a range
arr[0:5]

## Indexing a 2D array (matrices)

The general format is **arr_2d[row][col]** or **arr_2d[row,col]**. I recommend usually using the comma notation for clarity.

In [ ]:
### creating a 2-d array

arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

#Show
arr_2d

In [ ]:
### indexing row
arr_2d[1]

In [ ]:
### Format is arr_2d[row][col] or arr_2d[row,col]

### Getting individual element value
arr_2d[1][0]

In [ ]:
### getting individual element value
arr_2d[1,0]

In [ ]:
# 2D array slicing

### shape (2,2) from top right corner
arr_2d[:2,1:]

In [ ]:
#Shape bottom row
arr_2d[2]

In [ ]:
#Shape bottom row
arr_2d[2,:]

## Selection

Let's briefly go over how to use brackets for selection based off of comparison operators.

In [ ]:
arr = np.arange(1,11)
arr

In [ ]:
arr > 4

In [ ]:
bool_arr = arr>4

In [ ]:
bool_arr

In [ ]:
arr[bool_arr]

In [ ]:
arr[arr>2]

In [ ]:
x = 2
arr[arr>x]