# h03 NumPy - Solutions
In this homework, you will do:
- Python review: for loop & data collection operations
- NumPy array operations
- NumPy vectorized functions (**ufuncs**)

**Academic honor**:
1. Academic honor is important. Do your work, learn, **DON'T CHEAT!** 
2. <font color='darkred'>**Use AI to LEARN, not to cheat**. **DO NOT do copy-and-paste**</font>. 
3. Collaboration and using resources are encouraged, but DO NOT directly share answers.

In [1]:
### import numpy as np
import numpy as np

## 1. Programming Review
### 1.1. for loop with range

In [2]:
### use the range( ) function
### use the end= parameter when printing

for i in range(0, 10):
    print(i, end=" ")

0 1 2 3 4 5 6 7 8 9 

### 1.2. for loop with list

In [3]:
### use the range() function to create the sequence
### use the list function to cast the object list
### save the list to a variable named "lst"
### use a for loop to print the list elements (use the "in" keyword)
### use the end= parameter when printing

lst = list(range(10))
for i in lst:
    print(i, end=" ")

0 1 2 3 4 5 6 7 8 9 

## 1.3 dictionary

In [4]:
### Observe the hypothetical pocket change dictionary below. Note that a dictionary:
### use curly braces instead of square brackets like lists
### contains key: value pairs as elements

dict_money = {"Garrett": 1900, "Jase": 20000, "Quincy": 23000, "Canaan": 21000, "Rhea": 19000}

To access the value of a key, use the **bracket notation**.

In [5]:
dict_money['Garrett']

1900

How much money do Canaan and Rhea have in total?

In [6]:
dict_money['Canaan'] + dict_money['Rhea']

40000

## 2. NumPy Array Operations

In [7]:
### import numpy here if you haven't
import numpy as np

### 2.1 Creating NumPy Arrays: 1D (vector) & 2D (matrix)
Practicing array creation and attributes: 
- **dtype**,
- **ndim**, and
- **shape**.

### 2.1.1. Create a 1D array 
- and check the dimension of the array

In [8]:
### Use the numpy arrange function 
### assign the numpy array to a variable, call it "arr"

arr = np.arange(0, 10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
### check the dimension of the array
### use the ndmin attribute

arr.ndim

1

### 2.2.2. Create a 2D array 
- and check the shape of array

In [10]:
### Use the numpy arrange function 
### place a 2D list as the argument for the function
### assign the numpy array to a variable, call it "arr"

arr_2d = np.array([[1, 2, 3],
                [5, 5, 5],
                [7, 8, 9]])
arr_2d

array([[1, 2, 3],
       [5, 5, 5],
       [7, 8, 9]])

In [11]:
### check the shape of the array
### use the shape attribute

arr_2d.shape

(3, 3)

### 2.2.3. Data Type: Array ("ndarray") vs Scalar (e.g., "int64")
- Numpy has 24 data types for scalars
- Use the type() function and the dtype attribute

In [12]:
### check the data type of array
### you should see the data type is "numpy.ndarray"

type(arr_2d)

numpy.ndarray

In [13]:
### check the data type of array scalars
### use the dtype attribute
### you should see dtype('int64')

arr_2d.dtype

dtype('int64')

### 2.2.4. Array Creation: reshape()

learn how to use the
- **np.random.rand( )**,
- **randint( )**, and
- **np.random.seed( )** function

In [14]:
### create a 1D array with 24 elements 
### the elements are random float numbers between [0, 1). 
### use one of the random functions in the np.random module

arr = np.random.rand(24)
arr

array([0.93146352, 0.98309537, 0.465602  , 0.72511095, 0.03881467,
       0.60656881, 0.45465701, 0.11747097, 0.6945954 , 0.34933867,
       0.91504592, 0.59558548, 0.79424567, 0.96122039, 0.41754502,
       0.7141615 , 0.85172283, 0.54094721, 0.22281686, 0.92097374,
       0.3901305 , 0.05874695, 0.60562982, 0.50689723])

In [15]:
### reshape the array into a 6x4 2D array

arr_64 = arr.reshape(6, 4)
arr_64

array([[0.93146352, 0.98309537, 0.465602  , 0.72511095],
       [0.03881467, 0.60656881, 0.45465701, 0.11747097],
       [0.6945954 , 0.34933867, 0.91504592, 0.59558548],
       [0.79424567, 0.96122039, 0.41754502, 0.7141615 ],
       [0.85172283, 0.54094721, 0.22281686, 0.92097374],
       [0.3901305 , 0.05874695, 0.60562982, 0.50689723]])

In [16]:
### create a 1D array with 24 elements 
### the elements are random integers between [1, 100] (including 100)
### use one of the random functions in the np.random module

np.random.seed(100)     ### don't change the seed value
                        ### with the same seed value, the "randomly" 
                        ### generated values will be the same every time you run the code

arr_int = np.random.randint(1, 101, 24)
arr_int

array([ 9, 25, 68, 88, 80, 49, 11, 95, 53, 99, 54, 67, 99, 15, 35, 25, 16,
       61, 59, 17, 10, 94, 87,  3])

In [17]:
### reshape the 1D array into a 6x4 2D array, still call it arr_int

arr_int = arr_int.reshape(6, 4)
arr_int

array([[ 9, 25, 68, 88],
       [80, 49, 11, 95],
       [53, 99, 54, 67],
       [99, 15, 35, 25],
       [16, 61, 59, 17],
       [10, 94, 87,  3]])

## 2.2. Assessing Array Elements: Indexing and Slicing

In [18]:
### show the first row of the array arr_int

arr_int[0]

array([ 9, 25, 68, 88])

In [19]:
### slicing: select the two middle rows

arr_int[ 2:4, : ]      ### a different syntax: arr_int[2:4][:]

array([[53, 99, 54, 67],
       [99, 15, 35, 25]])

In [20]:
### slicing: select a subset

arr_int[2:, 1:]

array([[99, 54, 67],
       [15, 35, 25],
       [61, 59, 17],
       [94, 87,  3]])

## 3. Array Computation: ufuncs
- Array Arithmetic
- Array Aggregation

In [21]:
arr1 = np.arange(5)           ### 0...4
arr2 = np.arange(5, 10, 1)    ### 5...9
print("arr1 = ", arr1)
print("arr2 = ", arr2)

arr1 =  [0 1 2 3 4]
arr2 =  [5 6 7 8 9]


In [22]:
### addition: add arr1 and arr2

arr1 + arr2

array([ 5,  7,  9, 11, 13])

In [23]:
### subtraction: subtract arr2 from arr1

arr1 - arr2

array([-5, -5, -5, -5, -5])

In [24]:
### multiplication: times arr1 by arr2

arr1 * arr2

array([ 0,  6, 14, 24, 36])

In [25]:
### division: divide arr1 by arr2

arr1 / arr2

array([0.        , 0.16666667, 0.28571429, 0.375     , 0.44444444])

In [26]:
### min: check the minimum value of arr1

np.min(arr1)

np.int64(0)

In [27]:
### max: check the maximum value of arr1

np.max(arr1)

np.int64(4)

In [28]:
### mean: check the average of elements in arr1

np.mean(arr1)

np.float64(2.0)

In [29]:
### argmax(): check the index number of the largest value in arr1

arr1.argmax()

np.int64(4)

In [30]:
### sqrt(): take square root of arr1

np.sqrt(arr1)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ])