# h03 NumPy - Questions
In this homework, you will do:
- Python review: for loop & data collection operations
- NumPy array operations
- NumPy vectorized functions (**ufuncs**)

**Academic honor**:
1. Academic honor is important. Do your work, learn, **DON'T CHEAT!** 
2. <font color='darkred'>**Use AI to LEARN, not to cheat**. **DO NOT do copy-and-paste**</font>. 
3. Collaboration and using resources are encouraged, but DO NOT directly share answers.

In [1]:
### import numpy as np

##### change me #####

## 1. Programming Review
### 1.1. for loop with range

In [4]:
### use the range( ) function
### use the end= parameter when printing

##### change me #####:
    print(i, end=" ")

0 1 2 3 4 5 6 7 8 9 

### 1.2. for loop with list

In [246]:
### use the range() function to create the sequence
### use the list function to cast the object list
### save the list to a variable named "lst"
### use a for loop to print the list elements (use the "in" keyword)
### use the end= parameter when printing

lst = ##### change me #####
for ##### change me #####:
    print(i, end=" ")

0 1 2 3 4 5 6 7 8 9 

## 1.3 dictionary

In [247]:
### Observe the hypothetical pocket change dictionary below. Note that a dictionary:
### use curly braces instead of square brackets like lists
### contains key: value pairs as elements

dict_money = {"Garrett": 1900, "Jase": 20000, "Quincy": 23000, "Canaan": 21000, "Rhea": 19000}

To access the value of a key, use the **bracket notation**.

In [248]:
dict_money['Garrett']

1900

How much money do Canaan and Rhea have in total?

In [249]:
##### change me #####

40000

## 2. NumPy Array Operations

In [250]:
### import numpy here if you haven't
import numpy as np

### 2.1 Creating NumPy Arrays: 1D (vector) & 2D (matrix)
Practicing array creation and attributes: 
- **dtype**,
- **ndim**, and
- **shape**.

### 2.1.1. Create a 1D array 
- and check the dimension of the array

In [251]:
### Use the numpy arrange function 
### assign the numpy array to a variable, call it "arr"

arr = ##### change me #####
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [83]:
### check the dimension of the array
### use the ndmin attribute

arr.##### change me #####

1

### 2.2.2. Create a 2D array 
- and check the shape of array

In [91]:
### Use the numpy arrange function 
### place a 2D list as the argument for the function
### assign the numpy array to a variable, call it "arr"

arr_2d = np.array([[1, 2, 3],
                ##### change me #####
                ##### change me #####
arr_2d

array([[1, 2, 3],
       [5, 5, 5],
       [7, 8, 9]])

In [92]:
### check the shape of the array
### use the shape attribute

##### change me #####

(3, 3)

### 2.2.3. Data Type: Array ("ndarray") vs Scalar (e.g., "int64")
- Numpy has 24 data types for scalars
- Use the type() function and the dtype attribute

In [93]:
### check the data type of array
### you should see the data type is "numpy.ndarray"

##### change me #####(arr_2d)

numpy.ndarray

In [94]:
### check the data type of array scalars
### use the dtype attribute
### you should see dtype('int64')

arr_2d.##### change me #####

dtype('int64')

### 2.2.4. Array Creation: reshape()

learn how to use the
- **np.random.rand( )**,
- **randint( )**, and
- **np.random.seed( )** function

In [196]:
### create a 1D array with 24 elements 
### the elements are random float numbers between [0, 1). 
### use one of the random functions in the np.random module

arr = np.##### change me #####
arr

array([0.97862378, 0.81168315, 0.17194101, 0.81622475, 0.27407375,
       0.43170418, 0.94002982, 0.81764938, 0.33611195, 0.17541045,
       0.37283205, 0.00568851, 0.25242635, 0.79566251, 0.01525497,
       0.59884338, 0.60380454, 0.10514769, 0.38194344, 0.03647606,
       0.89041156, 0.98092086, 0.05994199, 0.89054594])

In [197]:
### reshape the array into a 6x4 2D array

arr_64 = arr.##### change me #####
arr_64

array([[0.97862378, 0.81168315, 0.17194101, 0.81622475],
       [0.27407375, 0.43170418, 0.94002982, 0.81764938],
       [0.33611195, 0.17541045, 0.37283205, 0.00568851],
       [0.25242635, 0.79566251, 0.01525497, 0.59884338],
       [0.60380454, 0.10514769, 0.38194344, 0.03647606],
       [0.89041156, 0.98092086, 0.05994199, 0.89054594]])

In [205]:
### create a 1D array with 24 elements 
### the elements are random integers between [1, 100] (including 100)
### use one of the random functions in the np.random module

np.random.seed(100)     ### don't change the seed value
                        ### with the same seed value, the "randomly" 
                        ### generated values will be the same every time you run the code

arr_int = np.random.##### change me #####
arr_int

array([ 9, 25, 68, 88, 80, 49, 11, 95, 53, 99, 54, 67, 99, 15, 35, 25, 16,
       61, 59, 17, 10, 94, 87,  3])

In [207]:
### reshape the 1D array into a 6x4 2D array, still call it raa_int

arr_int = arr_int.##### change me #####
arr_int

array([[ 9, 25, 68, 88],
       [80, 49, 11, 95],
       [53, 99, 54, 67],
       [99, 15, 35, 25],
       [16, 61, 59, 17],
       [10, 94, 87,  3]])

## 2.2. Assessing Array Elements: Indexing and Slicing

In [208]:
### show the first row of the array arr_int

arr_int[0]

array([ 9, 25, 68, 88])

In [218]:
### slicing: select the two middle rows

arr_int[ ##### change me ##### ]      ### a different syntax: arr_int[2:4][:]

array([[53, 99, 54, 67],
       [99, 15, 35, 25]])

In [219]:
### slicing: select a subset

arr_int[ ##### change me ##### ]

array([[99, 54, 67],
       [15, 35, 25],
       [61, 59, 17],
       [94, 87,  3]])

## 3. Array Computation: ufuncs
- Array Arithmetic
- Array Aggregation

In [236]:
arr1 = np.arange(5)           ### 0...4
arr2 = np.arange(5, 10, 1)    ### 5...9
print("arr1 = ", arr1)
print("arr2 = ", arr2)

arr1 =  [0 1 2 3 4]
arr2 =  [5 6 7 8 9]


In [224]:
### addition: add arr1 and arr2

##### change me #####

array([ 5,  7,  9, 11, 13])

In [228]:
### subtraction: subtract arr2 from arr1

##### change me #####

array([-5, -5, -5, -5, -5])

In [237]:
### multiplication: times arr1 by arr2

##### change me #####

array([ 0,  6, 14, 24, 36])

In [238]:
### division: divide arr1 by arr2

##### change me #####

array([0.        , 0.16666667, 0.28571429, 0.375     , 0.44444444])

In [239]:
### min: check the minimum value of arr1

##### change me #####

np.int64(0)

In [240]:
### max: check the maximum value of arr1

##### change me #####

np.int64(4)

In [241]:
### mean: check the average of elements in arr1

##### change me #####

np.float64(2.0)

In [243]:
### argmax(): check the index number of the largest value in arr1

##### change me #####

np.int64(4)

In [8]:
### sqrt(): take square root of arr1

np.sqrt(arr1)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ])