# NumPy Arrays Basics

NumPy arrays (n-dimensional array, or **`ndarray`**) are like a super-powered **list** that can store numbers in rows and columns. You will learn that some array operations are similar, if not the same, as Python lists.

NumPy arrays essentially come in two flavors, vectors and matrices:
- **Vectors** are strictly 1-d arrays that have only one axis, and
- **matrices** are 2-d arrays with two axes: (rows, columns).

Here in this section, we discuss topics regarding NumPy arrays:
- creation
- indexing/slicing
- general array attributes and functions such as ndim, dtype, shape, reshape

## Creating NumPy Arrays

### From a Python List

You can create an array by directly casting a list to an array. Let us create a list first:

In [1]:
nums_list = [1,2,3, 4, 5]
nums_list

[1, 2, 3, 4, 5]

In [2]:
type(nums_list)

list

Now let's cast the list into a numpy array using numpy's `array()` method to create a **1-D** array.

In [3]:
### before using numpy, import
### we usually import packages in the very beginning of a notebook

import numpy as np

In [4]:
arr = np.array(nums_list)       ### casting a list to a numpy array
arr

### now you will see a numpy array, which is different from the list [1, 2, 3]

array([1, 2, 3, 4, 5])

In [5]:
### data type is different from list too: numpy.ndarray 

type(arr)                   

numpy.ndarray

We can also place the Python list directly into the np.array function to create a NumPy array (note that this is a **2-D** array):

In [6]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


An example of Python **3-D** "array" (list of lists): 

In [7]:
list_of_list = [
    [
        [1, 2, 3, 4], 
        [2, 2, 3, 4], 
        [3, 2, 3, 4]
    ], 
    [
        [4, 2, 3, 4], 
        [5, 2, 3, 4], 
        [6, 2, 3, 4]
    ]
]
list_of_list

[[[1, 2, 3, 4], [2, 2, 3, 4], [3, 2, 3, 4]],
 [[4, 2, 3, 4], [5, 2, 3, 4], [6, 2, 3, 4]]]

Compare the result of evaluation of the Python list above with the NumPy array from the list:

In [8]:
np.array(list_of_list)

array([[[1, 2, 3, 4],
        [2, 2, 3, 4],
        [3, 2, 3, 4]],

       [[4, 2, 3, 4],
        [5, 2, 3, 4],
        [6, 2, 3, 4]]])

#### Using List Comprehension

Note the syntax of list comprehension is an alternative to for loops. Instead of initialize an empty list variable, running the for loop to append the elements, list comprehension is more concise. 

In [9]:
np.array([i**2 for i in range(10)])

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

### Using arange() Function

In [10]:
np.arange(5)

array([0, 1, 2, 3, 4])

Using the range parameters:

In [11]:
np.arange(2, 11, 2)

array([ 2,  4,  6,  8, 10])

### Using Functions: zeros(), ones(), and full()
These function initialize arrays of a specified shape filled with zeros, ones, or a constant value, respectively. The syntax for numpy.ones() function is:

<code>numpy.ones(shape, dtype=None, order='C', *, like=None)</code>

We pass the shape argument using a list or tuple. 

In [12]:
np.zeros((2, 3))        ### by default dtype is float

array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
np.ones([2,3], int)     ### dtype is int

array([[1, 1, 1],
       [1, 1, 1]])

In [14]:
np.full((2, 3), 5)      ### fill the shape (2x3) with 5

array([[5, 5, 5],
       [5, 5, 5]])

## NumPy Indexing and Selection

Just like Python lists, square brackets [] are used for selecting the elements or groups of elements from an array:
1. accessing individual elements of a list (**indexing**).
2. selecting sub-sequences (**slicing** with parameters: start, stop exclusive, and step). Note that slicing returns a numpy array.
3. **negative** indexing: begins with -1 from the end of the sequence.

In [15]:
import numpy as np

In [16]:
### creating sample array
arr = np.arange(0,10)

In [17]:
### show the array
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
### indexing 
arr[1]

np.int64(1)

In [19]:
arr[0:3]

array([0, 1, 2])

In [20]:
arr[0:5:2]

array([0, 2, 4])

In [21]:
arr[-1]

np.int64(9)

In [22]:
### start is -3, and stop is -1 exclusive
arr[-3:-1]

array([7, 8])

### Indexing/Slicing 2-D Aarrays (Matrices)

To access a 2-D array (matrices), use the syntax `array[row_index, column_index]`. The general format is **arr[row][col]** or **arr[row, col]**. 

In [52]:
### creating a 2-d array

arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [24]:
### 0-based indexing; 1st row
arr_2d[0]

array([ 5, 10, 15])

In [25]:
### 0-based indexing
arr_2d[1, 2]

np.int64(30)

In [26]:
### 2D array slicing
### shape (2,2) from top right corner

arr_2d[:2, 1:]

array([[10, 15],
       [25, 30]])

### One More Example: 2-D Array (Matrices)

In [27]:

arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

#Show
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [28]:
### indexing row
arr_2d[1]

array([20, 25, 30])

In [29]:
### Format is arr_2d[row][col] or arr_2d[row,col]

### Getting individual element value
arr_2d[1][0]

np.int64(20)

In [30]:
### getting individual element value
arr_2d[1,0]

np.int64(20)

In [31]:
# 2D array slicing

### shape (2,2) from top right corner
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [53]:
### shape bottom row
arr_2d[2]

array([35, 40, 45])

In [55]:
### also shape bottom row with colon
arr_2d[2,:]

array([35, 40, 45])

## NumPy Array Properties

### The shape Attribute

The shape attribute **returns a tuple** of integers at every index tells about the number of elements the corresponding dimension has.

In [114]:
arr_2d.shape

(3, 3)

In [115]:
arr_2d[:2, 1:].shape

(2, 2)

In [118]:
### create a 1-D array

arr_vec = np.arange(1, 10, 2)
arr_vec

array([1, 3, 5, 7, 9])

In [101]:
### a vector (an ordered list or an array of numbers, often 
### representing multiple related variables or observations)
arr_vec.shape

(5,)

In [139]:
### np.array([list comprehension])
arr_25 = np.array([ num for num in range(25)])
arr_25

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [140]:
arr_25.shape

(25,)

### The reshape() Function 
The reshape() function changes the shape of a NumPy array without altering its underlying data. It **returns a new array** (or a view of the original array if possible) with the specified new shape.

In [136]:
### arr
arr = np.array(
    [num for num in range(10)]
)

arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [137]:
# notice the two sets of brackets

arr = arr.reshape(2,5)
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [138]:
### this will not work

arr.reshape(5,5)

ValueError: cannot reshape array of size 10 into shape (5,5)

In [141]:
### back to arr_25

arr_25.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [145]:
arr_25.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [146]:
arr_25.reshape(5, 5).shape

(5, 5)

In [147]:
### reshape does not change the object

arr_25

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

### dtype

You can get the data type of the object in the array:

In [150]:
arr_25.dtype

dtype('int64')

### ndim
The ndim attribute represents the number of dimensions (or axes) of the array.

In [153]:
arr_25.ndim

1

In [154]:
arr_55 = arr_25.reshape(5, 5)
arr_55.ndim

2