# NumPy Array Computation

NumPy is so important in the Pythonic data science world because it optimizes computation with arrays.
Computational efficiency on NumPy arrays lies in the use of vectorized operations, generally implemented through NumPy’s [universal array functions](http://docs.scipy.org/doc/numpy/reference/ufuncs.html) (**ufuncs**). 

1. Basic arithmetic
2. Linear algebra
3. Random numbers

## Reason for Vectorized Operations

For element-wise operations like addition (see example below), you can simply use Python’s arithmetic operators directly on NumPy's array object. This vectorized method shifts the looping process to NumPy’s compiled layer, resulting in significantly faster execution.



### A Regular Iterative Operation
Let's take a look at a general iteration (**loop 5 times**) example (note the code is meant to represent a computation for your Python programming learning, not a business context):

In [12]:
import numpy as np
rng = np.random.default_rng(seed=1701)      ### default_rng() is a Random Number Generator
                                            ### it's a function in numpy's random module
                                            ### A random seed (or seed state, or just seed) 
                                            ### is a number (or vector) used to initialize 
                                            ### a pseudorandom number generator. 
                                            ### A pseudorandom number generator's number sequence 
                                            ### is completely determined by the seed: thus, if 
                                            ### a pseudorandom number generator is later reinitialized 
                                            ### with the same seed, it will produce the same sequence of numbers.
                                            ### https://en.wikipedia.org/wiki/Random_seed
def compute_reciprocals(values):
    output = np.empty(len(values))          ### numpy.empty() creates an array by taking whatever "garbage" values present in the allocated memory at the time of creation.
    for i in range(len(values)):            ### for loop update the elements of output array
        output[i] = 1.0 / values[i]
    return output                           ### return the output array
        
values = rng.integers(1, 10, size=5)
compute_reciprocals(values)
                                            ### when returned, Jupyter evaluates and outputs

array([0.11111111, 0.25      , 1.        , 0.33333333, 0.125     ])

In [13]:
### explains the code here
### rng function with seed
rng = np.random.default_rng(seed=1701)   

In [14]:
### the values
values = rng.integers(1, 10, size=5)
values

array([9, 4, 1, 3, 8])

In [15]:
### the output 
np.empty(len(values))

array([4.4e-323, 2.0e-323, 4.9e-324, 1.5e-323, 4.0e-323])

In [16]:
### output 
output = np.empty(len(values))

In [17]:
### loop through to update the output array
for i in range(len(values)):
   output[i] = 1.0 / values[i]
print( output)

[0.11111111 0.25       1.         0.33333333 0.125     ]


Now calling the function with a huge number: **1000000**

In [18]:
big_array = rng.integers(1, 100, size=1000000)
%timeit compute_reciprocals(big_array)

### μs is one-millionth of a second (10⁻⁶ s); a ns is one billionth of a second (10⁻⁹ s)

523 ms ± 2.97 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


### Lists vs Arrays
An example comparing list iteration and vectorized operation. 

(The following sample code is adapted from [geeksforgeeks](https://www.geeksforgeeks.org/numpy/vectorized-operations-in-numpy/).)

In [19]:
import numpy as np
import time

lst = list(range(1000000))   ### create list
start_time = time.time()     ### time starts
# iterative_sum = sum(range(15000))          ###geeksforgeeks got it wrong here.
iterative_sum = sum(lst)     ### sum list
print("\nIterative sum:", iterative_sum)
print("Time taken by iterative sum:", time.time() - start_time)
iterative_time = time.time() - start_time

arr = np.arange(1000000)     ### create array
start_time = time.time()     ### time starts
vectorized_sum = np.sum(arr) ### sum array
print("Vectorized sum:", vectorized_sum)
print("Time taken by vectorized sum:", time.time() - start_time)
vectoized_time = time.time() - start_time

print()

print(f"NumPy array sum is {iterative_time / vectoized_time:.2f} times faster of list sum.")


Iterative sum: 499999500000
Time taken by iterative sum: 0.0022199153900146484
Vectorized sum: 499999500000
Time taken by vectorized sum: 0.00016307830810546875

NumPy array sum is 12.59 times faster of list sum.


## Array Arithmetic ufuncs

Ufuncs come in two types: **unary** ufuncs, which work with a single input, and **binary ufuncs**, which work with two inputs. We’ll explore examples of both types in this section.

NumPy implements arithmetic operators with ufuncs as follows. But NumPy ufuncs makes use of Python's native arithmetic operators as well, which is more intuitive to use.

```python
+  np.add          Addition (e.g., 1 + 1 = 2)
-  np.subtract     Subtraction (e.g., 3 - 2 = 1)
-  np.negative     Unary negation (e.g., -2)
*  np.multiply     Multiplication (e.g., 2 * 3 = 6)
/  np.divide       Division (e.g., 3 / 2 = 1.5)
// np.floor_divide Floor division (e.g., 3 // 2 = 1)
** np.power        Exponentiation (e.g., 2 ** 3 = 8)
%  np.mod          Modulus/remainder (e.g., 9 % 4 = 1)
```

In [20]:
arr1 = np.arange(5)           ### 0...4
arr2 = np.arange(5, 10, 1)    ### 5...9

print(np.add(arr1, arr2))
print(np.subtract(arr1, arr2))
print(np.negative(arr1))
print(np.multiply(arr1, arr2))
print(np.divide(arr1, arr2))
print(np.floor_divide(arr1, 3))
print(np.ceil(np.floor_divide(arr1, 2)))
print(np.power(arr1, 3))
print(np.mod(arr1, 2))

[ 5  7  9 11 13]
[-5 -5 -5 -5 -5]
[ 0 -1 -2 -3 -4]
[ 0  6 14 24 36]
[0.         0.16666667 0.28571429 0.375      0.44444444]
[0 0 0 1 1]
[0 0 1 1 2]
[ 0  1  8 27 64]
[0 1 0 1 0]


Similar vectorized operations can be achieved using the Python arithmetic operators.

In [21]:
### create array using np.arange() function
arr = np.arange(0,10)

In [22]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
### addition
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [24]:
### multiplication
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [25]:
### substration
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [26]:
### check array: unchanged after operations because we didn't change the reference
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
### division by zero!!! 
### However, unlike Python, you do not receive an error.
### Just replaced with nan
arr / arr

/var/folders/6t/bfp06fh96wn60n_mjtxmbhfm0000gn/T/ipykernel_65374/1831715423.py:4: RuntimeWarning: invalid value encountered in divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In NumPy, `np.nan` represents "Not a Number," a special floating-point value defined by the IEEE 754 standard. It signifies missing or undefined numerical data, such as the result of an indeterminate mathematical operation (e.g., dividing zero by zero).

In [28]:
### also warning, but not an error, instead infinity
1 / arr

/var/folders/6t/bfp06fh96wn60n_mjtxmbhfm0000gn/T/ipykernel_65374/2426921330.py:2: RuntimeWarning: divide by zero encountered in divide
  1 / arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

Seeing the operation in the terminal, you will see the **inf** and **nan** as output.
```python
>>> arr = np.arange(5)
>>> arr
array([0, 1, 2, 3, 4])
>>> arr[0]/1
np.float64(0.0)
>>> print(arr[0]/1)
0.0
>>> print(arr[1]/0)
<python-input-13>:1: RuntimeWarning: divide by zero encountered in scalar divide
inf
>>> 
>>> print(arr[0]/0)
<python-input-14>:1: RuntimeWarning: invalid value encountered in scalar divide
nan
```

In [29]:
### exponentiation
arr**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [30]:
### summary: ufunc arithmetic operators

x = np.arange(5)
print("x =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x // 2 =", x // 2) # floor division

x = [0 1 2 3 4]
x + 5 = [5 6 7 8 9]
x - 5 = [-5 -4 -3 -2 -1]
x * 2 = [0 2 4 6 8]
x / 2 = [0.  0.5 1.  1.5 2. ]
x // 2 = [0 0 1 1 2]


## More ufuncs

Numpy comes with many mathematical ufuncs, which are essentially just mathematical operations you can use to operate on the arrays.

In [31]:
### taking square roots
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [32]:
### exponential 1
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [33]:
### exponential 2: you can also do 
np.power(2, 3)

np.int64(8)

In [34]:
### exponential 2: or use the power function
np.power(arr, 3)

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [35]:
### exponential 3: or the ** operator
arr**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

#### Aggregation

In [36]:
### sum
arr_a = np.arange(5)
arr_b = np.arange(5, 10)
print(arr_a)
print(arr_b)
# # print(np.sum(arr1, arr2))
# print(np.sum(arr_a))  ### np.sum(), much faster
# print(sum(arr_a))     ### Python sum, the same as np.sum() with simple cases
# print(arr_a + arr_b)  ### ufunc
### if you Python sum(arr), you get an error: can't iterate
print(sum(arr_a, arr_b))     ### python sum
print(np.sum([arr_a, arr_b], axis=0))


[0 1 2 3 4]
[5 6 7 8 9]
[15 16 17 18 19]
[ 5  7  9 11 13]


In [37]:
### same as arr.max() method
arr = np.arange(5)
np.max(arr)

np.int64(4)

In [38]:
### min
print(np.min(arr))

0


In [39]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [40]:
np.log(arr)

/var/folders/6t/bfp06fh96wn60n_mjtxmbhfm0000gn/T/ipykernel_65374/3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])

## Lists: Element-By-Element Operations

In [41]:
### this is a range
range(5)

range(0, 5)

In [42]:
### type of range
type(range(5))

range

In [43]:
### use the list function/constructor to cast the range into a list
list(range(5))

[0, 1, 2, 3, 4]

In [44]:
### create a list variable to reference the object
lst = list(range(5))

In [45]:
### evaluate
lst

[0, 1, 2, 3, 4]

In [46]:
### check type
type(lst)

list

In [47]:
### this is very different from NumPy arrays
### this is very different from NumPy arrays
### this is very different from NumPy arrays

lst * 2

[0, 1, 2, 3, 4, 0, 1, 2, 3, 4]

In [48]:
print(lst * 2)

[0, 1, 2, 3, 4, 0, 1, 2, 3, 4]


In [49]:
arr = np.array([1, 2, 3, 4])
print(arr * 2)              # multiply each element by 2
print(arr + 5)              # add 5 to each element

[2 4 6 8]
[6 7 8 9]


### Broadcasting

NumPy can combine arrays of different shapes by \"stretching\" one to match the other.

In [50]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([10, 20, 30])

print(A + B)

[[11 22 33]
 [14 25 36]]


## Built-in Functions

There are lots of built-in ways to generate Arrays

### arange

Return evenly spaced values within a given interval.

In [51]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [ ]:
ranarr

In [ ]:
ranarr.max()

In [ ]:
ranarr.argmax()

In [ ]:
ranarr.min()

In [ ]:
ranarr.argmin()

## Broadcasting

Numpy arrays differ from a normal Python list because of their ability to broadcast:

In [ ]:
#Setting a value with index range (Broadcasting)
arr[0:5]=100

#Show
arr

In [ ]:
# Reset array, we'll see why I had to reset in  a moment
arr = np.arange(0,11)

#Show
arr

In [ ]:
#Important notes on Slices
slice_of_arr = arr[0:6]

#Show slice
slice_of_arr

In [ ]:
#Change Slice
slice_of_arr[:]=99

#Show Slice again
slice_of_arr

Now note the changes also occur in our original array!

In [ ]:
arr

Data is not copied, it's a view of the original array! This avoids memory problems!

In [ ]:
#To get a copy, need to be explicit
arr_copy = arr.copy()

arr_copy

### Fancy Indexing

Fancy indexing allows you to select entire rows or columns out of order,to show this, let's quickly build out a numpy array:

In [ ]:
#Set up matrix
arr2d = np.zeros((10,10))

In [ ]:
#Length of array
arr_length = arr2d.shape[1]

In [ ]:
#Set up array

for i in range(arr_length):
    arr2d[i] = i
    
arr2d

Fancy indexing allows the following

In [ ]:
arr2d[[2,4,6,8]]

In [ ]:
#Allows in any order
arr2d[[6,4,2,7]]

## Selection

Let's briefly go over how to use brackets for selection based off of comparison operators.

In [ ]:
arr = np.arange(1,11)
arr

In [ ]:
arr > 4

In [ ]:
bool_arr = arr>4

In [ ]:
bool_arr

In [ ]:
arr[bool_arr]

In [ ]:
arr[arr>2]

In [ ]:
x = 2
arr[arr>x]