In [1]:
import numpy as np

In [2]:
nums_list = [1,2,3]
nums_list

[1, 2, 3]

In [3]:
type(nums_list)

list

In [4]:
arr = np.array(nums_list)       ### casting a list to a numpy array
arr

array([1, 2, 3])

In [5]:
type(arr)                   ### data type: numpy.ndarray 

numpy.ndarray

In [6]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [7]:
list_of_list = [[1,2,3],[4,5,6],[7,8,9]]
list_of_list

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
np.array(list_of_list)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
arr = np.array([1, 2, 3, 4])
print(arr * 2)              # multiply each element by 2
print(arr + 5)              # add 5 to each element

[2 4 6 8]
[6 7 8 9]


In [10]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([10, 20, 30])

print(A + B)

[[11 22 33]
 [14 25 36]]


In [11]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [13]:
np.zeros(3)

array([0., 0., 0.])

In [14]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
np.ones(3)

array([1., 1., 1.])

In [16]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [17]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [18]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [19]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [20]:
np.random.rand(5)

array([0.7662703 , 0.36096001, 0.33931296, 0.82565943, 0.38581859])

In [21]:
np.random.rand(5,5)

array([[0.94679623, 0.19557905, 0.26884244, 0.68662496, 0.75697129],
       [0.8523132 , 0.40111978, 0.441093  , 0.02249067, 0.19144965],
       [0.31300895, 0.28219986, 0.46884137, 0.30148677, 0.81371731],
       [0.38273319, 0.34355071, 0.78321137, 0.14253147, 0.88746205],
       [0.79132813, 0.68586195, 0.23678168, 0.92244114, 0.48838177]])

In [22]:
np.random.randn(5)

array([-1.40395935, -0.62636832,  0.19816948,  0.06647995,  2.63143991])

In [23]:
np.random.randn(5,5)

array([[-0.59416496,  0.05196251, -0.71489311,  0.65485028, -0.74469763],
       [ 0.73010676, -0.19879899, -0.44934108,  2.04308074,  2.23711399],
       [-0.91111112,  0.95572147,  0.83369311, -1.4072904 , -0.02539006],
       [ 0.12347015,  1.43396602,  0.35241489, -1.75967405,  0.24800935],
       [ 1.20917481,  0.45094042, -0.51134639, -0.54455714, -0.24954165]])

In [24]:
np.random.randint(1,100)

96

In [25]:
np.random.randint(1,100,10)

array([73, 59,  5,  2, 63,  3, 82, 85,  7,  3])

In [26]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [27]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [28]:
ranarr

array([40, 46, 45, 15, 26,  8,  1, 21, 19,  5])

In [29]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [30]:
ranarr

array([40, 46, 45, 15, 26,  8,  1, 21, 19,  5])

In [31]:
ranarr.max()

np.int64(46)

In [32]:
ranarr.argmax()

np.int64(1)

In [33]:
ranarr.min()

np.int64(1)

In [34]:
ranarr.argmin()

np.int64(6)

In [35]:
# Vector
arr.shape

(25,)

In [36]:
# Notice the two sets of brackets
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [37]:
arr.reshape(1,25).shape

(1, 25)

In [38]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [39]:
arr.reshape(25,1).shape

(25, 1)

In [40]:
arr.dtype

dtype('int64')

In [41]:
import numpy as np

In [42]:
### creating sample array
arr = np.arange(0,11)

In [43]:
### show the array
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [44]:
#Get a value at an index
arr[8]

np.int64(8)

In [45]:
#Get values in a range
arr[1:5]

array([1, 2, 3, 4])

In [46]:
#Get values in a range
arr[0:5]

array([0, 1, 2, 3, 4])

In [47]:
#Setting a value with index range (Broadcasting)
arr[0:5]=100

#Show
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [48]:
# Reset array, we'll see why I had to reset in  a moment
arr = np.arange(0,11)

#Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [49]:
#Important notes on Slices
slice_of_arr = arr[0:6]

#Show slice
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [50]:
#Change Slice
slice_of_arr[:]=99

#Show Slice again
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [51]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [52]:
#To get a copy, need to be explicit
arr_copy = arr.copy()

arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [53]:
### creating a 2-d array

arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

#Show
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [54]:
### indexing row
arr_2d[1]

array([20, 25, 30])

In [55]:
### Format is arr_2d[row][col] or arr_2d[row,col]

### Getting individual element value
arr_2d[1][0]

np.int64(20)

In [56]:
### getting individual element value
arr_2d[1,0]

np.int64(20)

In [57]:
# 2D array slicing

### shape (2,2) from top right corner
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [58]:
#Shape bottom row
arr_2d[2]

array([35, 40, 45])

In [59]:
#Shape bottom row
arr_2d[2,:]

array([35, 40, 45])

In [60]:
#Set up matrix
arr2d = np.zeros((10,10))

In [61]:
#Length of array
arr_length = arr2d.shape[1]

In [62]:
#Set up array

for i in range(arr_length):
    arr2d[i] = i
    
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [63]:
arr2d[[2,4,6,8]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [64]:
#Allows in any order
arr2d[[6,4,2,7]]

array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.]])

In [65]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [66]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [67]:
bool_arr = arr>4

In [68]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [69]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [70]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [71]:
x = 2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])