In [1]:
import numpy as np

In [2]:
nums_list = [1,2,3]
nums_list

[1, 2, 3]

In [3]:
type(nums_list)

list

In [4]:
arr = np.array(nums_list)       ### casting a list to a numpy array
arr

array([1, 2, 3])

In [5]:
type(arr)                   ### data type: numpy.ndarray 

numpy.ndarray

In [6]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [7]:
list_of_list = [[1,2,3],[4,5,6],[7,8,9]]
list_of_list

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
np.array(list_of_list)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
arr = np.array([1, 2, 3, 4])
print(arr * 2)              # multiply each element by 2
print(arr + 5)              # add 5 to each element

[2 4 6 8]
[6 7 8 9]


In [10]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([10, 20, 30])

print(A + B)

[[11 22 33]
 [14 25 36]]


In [11]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [13]:
np.zeros(3)

array([0., 0., 0.])

In [14]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
np.ones(3)

array([1., 1., 1.])

In [16]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [17]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [18]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [19]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [20]:
np.random.rand(5)

array([0.89776128, 0.75521975, 0.56774828, 0.50529306, 0.15724666])

In [21]:
np.random.rand(5,5)

array([[0.66341915, 0.23192728, 0.82118164, 0.26350067, 0.8371965 ],
       [0.72342456, 0.71737886, 0.51335267, 0.60773009, 0.01460349],
       [0.95160508, 0.7608117 , 0.20011003, 0.479819  , 0.4893024 ],
       [0.41387962, 0.79440881, 0.5891401 , 0.05981543, 0.31422168],
       [0.2874105 , 0.86308322, 0.6343874 , 0.47933234, 0.80104912]])

In [22]:
np.random.randn(5)

array([ 0.0087182 , -1.18209126, -0.46226331, -1.21192853, -1.36074318])

In [23]:
np.random.randn(5,5)

array([[-0.94037997, -0.23810166, -1.80916462, -0.73354798, -0.8377706 ],
       [ 1.04477262,  0.61530641, -1.01532673, -0.10384582, -0.5890151 ],
       [ 0.67167589,  1.08718484,  0.2330294 ,  2.12422682, -1.114873  ],
       [-1.01810132,  1.04325916, -0.91965907, -0.25447486,  0.44547035],
       [-1.61451493,  0.86983261, -0.00415268, -0.90731259, -0.22382309]])

In [24]:
np.random.randint(1,100)

46

In [25]:
np.random.randint(1,100,10)

array([24,  2, 97, 30,  1, 96, 52, 41, 76, 36])

In [26]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [27]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [28]:
ranarr

array([25,  8,  1, 37, 49,  5,  3, 36, 10, 44])

In [29]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [30]:
ranarr

array([25,  8,  1, 37, 49,  5,  3, 36, 10, 44])

In [31]:
ranarr.max()

np.int64(49)

In [32]:
ranarr.argmax()

np.int64(4)

In [33]:
ranarr.min()

np.int64(1)

In [34]:
ranarr.argmin()

np.int64(2)

In [35]:
# Vector
arr.shape

(25,)

In [36]:
# Notice the two sets of brackets
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [37]:
arr.reshape(1,25).shape

(1, 25)

In [38]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [39]:
arr.reshape(25,1).shape

(25, 1)

In [40]:
arr.dtype

dtype('int64')