# h04 Pandas - Solutions
In this homework, you will do:
- Python review: for loop & data collection operations
- NumPy array operations
- Pandas Operations

**Academic honor**:
1. Academic honor is important. Do your work, learn, **DON'T CHEAT!** 
2. <font color='darkred'>**Use AI to LEARN, not to cheat**. **DO NOT do copy-and-paste**</font>. 
3. Collaboration and using resources are encouraged, but DO NOT directly share answers.

In [23]:
### import libraries

import numpy as np              ### import numpy
import pandas as pd             ### import pandas

## 1. Programming Review

- All the programming knowledge (e.g., data types, data structure...) and skills (e.g., loops, functions) are covered in the programming classes you took previously. 
- This is a review. 

### 1.1. for loop with list

In [24]:
### create a list following the instructions below

lst1 = list(range(1, 10))       ### use the range() function to create the a list called lst1
lst2 = []                       ### create an empty list, lst2, to save the results  
for i in lst1:                  ### a for loop to loop through the elements in lst1 
    if i % 2 == 0:              ### if the element is even
        lst2.append(i**2)       ### append the square of the element to lst2
                                ###
print(lst2, end=" ")            ### print the results in lst2; use the end= parameter when printing   

[4, 16, 36, 64] 

### 1.2. for loop with list comprehension

In [25]:
### create a list (lst3) using list comprehension following the instructions below

lst3 = [i**2 for i in lst1 if i % 2 == 0]   ### create a list comprehension to generate the same results as lst2
print(lst3, end=" ")                        ### print the results in lst3; use the end= parameter when printing

[4, 16, 36, 64] 

### 1.3. dictionary

In [26]:
### create a dictionary, call it fruit_price, containing 
### apple, banana, cherry as keys and 3, 4, 5 as prices (values)

fruit_price = {
    "apple": 3,
    "banana": 4,
    "cherry": 5
}

print(fruit_price['banana'])   ### print the price of banana

4


## 2. NumPy Array Operations

### 2.1 NumPy Vector

In [27]:
### create a numpy array, call it arr1, from the list lst1
arr1 = np.array(lst1)           ### create a numpy array from lst1
print(arr1)                     ### print the array
print(type(arr1))               ### print the data type of the array
print(arr1.dtype)               ### print the dtype of the array elements
print(arr1.ndim)                ### print the number of dimensions of the array
print(arr1.shape)               ### print the shape of the array
print(arr1[5])                  ### print the element at index 5 (the 6th element)
print(arr1 + arr1)              ### 
print(arr1 * 5)

[1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
int64
1
(9,)
6
[ 2  4  6  8 10 12 14 16 18]
[ 5 10 15 20 25 30 35 40 45]


### 2.2. NumPy Matrix

In [45]:
### create a numpy vector called v using the arange function
### v should contain integers from 0 to 19 

v = np.arange(0, 20)            ### create vector v
arr2 = v.reshape(4, 5)          ### create arr2 to a 4 x 5 matrix use reshape function
print(arr2)                     ### print the 2D array
print(type(arr2))               ### print the data type of the matrix
print(arr2.dtype)               ### print the data type of the array elements
print(arr2.ndim)                ### print the number of dimensions of arr2
print(arr2.shape)               ### print the shape of arr2
print(arr2[0:2, 3:])            ### print a subset of the matrix

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
<class 'numpy.ndarray'>
int64
2
(4, 5)
[[3 4]
 [8 9]]


## 3. Pandas Operations

### 3.1. Pandas Series

In [48]:
### create a Pandas Series using lst3, call it ser

ser = pd.Series(lst3)           ### create the Pandas Series
print(ser)                      ### print the Series

0     4
1    16
2    36
3    64
dtype: int64


### 3.2. Read File

In [52]:
### create a Pandas DataFrame, call it df, using arr2
### use the following column names: A, B, C, D, E

df = pd.DataFrame(arr2, columns=['A', 'B', 'C', 'D', 'E'])   ### create the DataFrame
print(df)                                                    ### print the DataFrame    

    A   B   C   D   E
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19


## 3. Array Computation: ufuncs
- Array Arithmetic
- Array Aggregation