# quiz py-np-pd-2 - Solutions

This quiz reviews your knowledge and skills in:
- Python review: for loop & function
- NumPy array operations
- Pandas Operations

In [1]:
### import libraries

import numpy as np
import pandas as pd

### 1. for loop with function

In [10]:
### create a list following the instructions below
### using list comprehension OR a for loop
### a for loop will take more lines of code, so I leave more space for that
### you can choose either method; name it square_evens

### list comprehension version
def square_evens(nums):             ### define function; takes a list as input
    return [num for num in nums if num%2 == 0]      ### return a list of squares of even numbers

### for loop version
def square_evens(nums):             ### define function; takes a list as input
    results = []                    ### create an empty list to store results
    for num in nums:                ### iterate through each number in the input list
        if num % 2 == 0:            ### check if the number is even
            results.append(num**2)  ### if even, append its square to the results list
    return results                  ### return the list of squared even numbers

nums = list( range(1, 10) )         ### create a list of numbers from 1 to 9       
results = square_evens(nums)        ### call the function with the list

for num in results:                 ### iterate through the results
    print(num, end=" ")             ### print each squared even number followed by a space   

4 16 36 64 

### 1.3. dictionary

In [3]:
### create a dictionary, call it fruit_price, containing 
### apple, banana, cherry as keys with lists of prices (values)

fruit_price = {
    'apple': [3, 2, 3],           ### the price of apple is a list [3, 2, 3]
    'banana': [4, 5, 4],          ### the price of banana is a list [4, 5, 4]
    'cherry': [5, 5, 5]           ### the price of cherry is a list [5, 5, 5]
}

print(fruit_price['banana'])   ### print the price of banana

[4, 5, 4]


### 2.2. NumPy Matrix

In [4]:
### create a numpy vector called v using the arange function
### v should contain integers from 0 to 19 

v = np.arange(20)           ### create vector v
arr2 = v.reshape(4, 5)      ### create arr2 to a 4 x 5 matrix use reshape function
print(arr2)                 ### print the 2D array
print(arr2.dtype)           ### print the data type of the matrix
print(arr2.dtype.type)      ### print the data type of the array elements
print(arr2.ndim)            ### print the number of dimensions of arr2
print(arr2.shape)           ### print the shape of arr2
print(arr2[1, 2])           ### print a subset of the matrix

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
int64
<class 'numpy.int64'>
2
(4, 5)
7


### 3.3. Create Pandas DataFrame

In [5]:
### create a Pandas DataFrame, call it df, using arr2
### use the following column names: A, B, C, D, E

df = pd.DataFrame(arr2, columns=['A', 'B', 'C', 'D', 'E'])  ### create the DataFrame
print(df)                                                   ### print the DataFrame    

    A   B   C   D   E
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19


### 3.5. Missing Data


In [6]:
### create a DataFrame, call it df, with missing data
### use the following data

df = pd.DataFrame({                     ### create the DataFrame
    'A' : [ 1, 2, np.nan ],             ### np.nan means "Not a Number", i.e., missing data
    'B' : [ 5, np.nan, np.nan],         
    'C' : [ 1, 2, 3]
    })

In [7]:
print(df)                                     ### print the DataFrame

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3


In [8]:
### detect the missing data in DataFrame df using the isna() method

print(df.isna(), "\n")          ### detect the missing data in DataFrame df using the isna() method
print(df.isna().sum(), "\n")    ### print the number of missing data in each column
print(df.fillna(0), "\n")       ### fill the missing data with 0 and print the DataFrame

       A      B      C
0  False  False  False
1  False   True  False
2   True   True  False 

A    1
B    2
C    0
dtype: int64 

     A    B  C
0  1.0  5.0  1
1  2.0  0.0  2
2  0.0  0.0  3 

