In [1]:
import numpy as np

In [2]:
nums_list = [1,2,3]
nums_list

[1, 2, 3]

In [3]:
type(nums_list)

list

In [4]:
arr = np.array(nums_list)       ### casting a list to a numpy array
arr

array([1, 2, 3])

In [5]:
type(arr)                   ### data type: numpy.ndarray 

numpy.ndarray

In [6]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [7]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
arr = np.array([1, 2, 3, 4])
print(arr * 2)              # multiply each element by 2
print(arr + 5)              # add 5 to each element

[2 4 6 8]
[6 7 8 9]


In [10]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([10, 20, 30])

print(A + B)

[[11 22 33]
 [14 25 36]]
