# quiz py-np-pd - Questions

This quiz reviews your knowledge and skills in:
- Python review: for loop & data collection operations
- NumPy array operations
- Pandas Operations

In [ ]:
### import libraries

### assuming all necessary libraries are imported

### 1.1. for loop with list

In [ ]:
### create a list following the instructions below

lst1 =  ##### change me #####               ### use the range() function to create the a list called lst1
lst2 =  ##### change me #####               ### create an empty list, lst2, to save the results  
for     ##### change me #####               ### a for loop to loop through the elements in lst1 
        ##### change me #####               ### if the element is even
        ##### change me #####               ### append the square of the element to lst2
                                            ###
print( ##### change me ##### )              ### print the results in lst2; use the end= parameter when printing   

[4, 16, 36, 64] 

### 1.2. for loop with list comprehension

In [ ]:
### create a list (lst3) using list comprehension following the instructions below

lst3 = ##### change me #####            ### create a list comprehension to generate the same results as lst2
print(lst3, end=" ")                    ### print the results in lst3; use the end= parameter when printing

[4, 16, 36, 64] 

### 1.3. dictionary

In [ ]:
### create a dictionary, call it fruit_price, containing 
### apple, banana, cherry as keys with lists of prices (values)

fruit_price = {
    ##### change me #####           ### the price of apple is a list [3, 2, 3]
    ##### change me #####           ### the price of banana is a list [4, 5, 4]
    ##### change me #####           ### the price of cherry is a list [5, 5, 5]
}

print(fruit_price['banana'])   ### print the price of banana

[4, 5, 4]


### 2.2. NumPy Matrix

In [ ]:
### create a numpy vector called v using the arange function
### v should contain integers from 0 to 19 

v = ##### change me #####           ### create vector v
arr2 = ##### change me #####        ### create arr2 to a 4 x 5 matrix use reshape function
print(arr2)                         ### print the 2D array
print(##### change me #####)        ### print the data type of the matrix
print(##### change me #####)        ### print the data type of the array elements
##### change me #####               ### print the number of dimensions of arr2
##### change me #####               ### print the shape of arr2
##### change me #####               ### print a subset of the matrix

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
<class 'numpy.ndarray'>
int64
2
(4, 5)
[[3 4]
 [8 9]]


### 3.3. Create Pandas DataFrame

In [ ]:
### create a Pandas DataFrame, call it df, using arr2
### use the following column names: A, B, C, D, E

df = ##### change me #####                                  ### create the DataFrame
print(df)                                                   ### print the DataFrame    

    A   B   C   D   E
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19


### 3.5. Missing Data


In [ ]:
### create a DataFrame, call it df, with missing data
### use the following data

df = pd.DataFrame({                     ### create the DataFrame
    'A' : [ 1, 2, np.nan ],             ### np.nan means "Not a Number", i.e., missing data
    'B' : [ 5, np.nan, np.nan],         
    'C' : [ 1, 2, 3]
    })

In [32]:
print(df)                                     ### print the DataFrame

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3


In [ ]:
### detect the missing data in DataFrame df using the isna() method
print(##### change me #####, "\n")          ### detect the missing data in DataFrame df using the isna() method
print(##### change me #####, "\n")          ### print the number of missing data in each column
print(##### change me #####, "\n")          ### fill the missing data with 0 and print the DataFrame

       A      B      C
0  False  False  False
1  False   True  False
2   True   True  False 

A    1
B    2
C    0
dtype: int64 

     A    B  C
0  1.0  5.0  1
1  2.0  0.0  2
2  0.0  0.0  3 

