In [6]:
import numpy as np

In [7]:
arr1 = np.array([1, 2, 3, 4, 5, 5])
print(arr1.shape)

(6,)


In [8]:
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2.shape)

(2, 3)


In [9]:
arr = np.array([1, 2, 3, 4], ndmin=5)

In [10]:
print(arr)
print('shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


In [11]:
arr

array([[[[[1, 2, 3, 4]]]]])

In [13]:
np.array([1, 2, 3, 4, 5], ndmin=2)

array([[1, 2, 3, 4, 5]])

In [14]:
[
    [
        [
            [
                [ 1, 2, 3, 4 ]
                ]
            ]
        ]
    ]

[[[[[1, 2, 3, 4]]]]]