In [2]:
from numpy import random

## random.randint()

In [132]:
for i in range (0, 11):
    rand = random.randint(100)
    print(rand, end=" ")

20 88 59 34 64 88 21 24 26 83 79 

In [142]:
for i in range(1, 4):
    rand = random.randint(0, 10)
    print(rand, end="\t")
    # print(i)

3	3	7	

## random.rand()

In [24]:
### random float: rand()
for i in range(1, 4):
    rand_float = random.rand()
    print(rand_float)
print()

for i in range(1, 4):
    rand_float = random.rand(2)
    print(rand_float)
print()

for i in range(1, 4):
    rand_float = random.rand(3, 2) # one row, each row contains 4 random numbers
    print(rand_float)

0.7394824429474146
0.9151804799484996
0.6620332050880536

[0.70525859 0.56545059]
[0.07882839 0.69940174]
[0.84761138 0.92194969]

[[0.38011    0.98710703]
 [0.33696304 0.22271584]
 [0.97106616 0.84293926]]
[[0.38463406 0.26702759]
 [0.8630411  0.33632579]
 [0.12034008 0.10483996]]
[[0.63786143 0.52836719]
 [0.96118867 0.9542779 ]
 [0.34734086 0.98339294]]


In [18]:
for i in range(1, 6):
    rand_float = random.rand()
    print(rand_float)

0.6800977810812358
0.9748756588610977
0.5029453304899165
0.3161800553251528
0.9116702607397614


## random.randn()