# NumPy Arrays Basics

NumPy arrays (n-dimensional array, or **`ndarray`**) are like a super-powered **list** that can store numbers in rows and columns. You will learn that some array operations are similar, if not the same, as Python lists.

NumPy arrays essentially come in two flavors, vectors and matrices:
- **Vectors** are strictly 1-d arrays that have only one axis, and
- **Matrices** are 2-d arrays with two axes: (rows, columns).

Here in this section, we discuss topics regarding NumPy arrays:
- creation
- indexing/slicing
- general array attributes and functions such as ndim, dtype, shape, reshape()


## NumPy Data Structure

The primary data structure in NumPy is the N-dimensional array, or **`ndarray`**. NumPy's arrays are a list of lists in Python, but are more compact than Python lists. In essence, a Python list is an array of pointers to heterogeneous Python objects, while a NumPy array is an array of **uniform** values of the same type (e.g., all integers, all floats) and array elements are stored in one continuous block of memory, similar to how arrays work in C ({numref}`c-vs-python-list`). Python lists are more flexible, but Numpy arrays are smaller in file size, and access in reading and writing items is much faster {cite}`Martelli_2009`.

<!-- , at least 4 bytes per pointer plus 16 bytes for even the smallest Python object (4 for type pointer, 4 for reference count, 4 for value -- and the memory allocators rounds up to 16).  -->

<!-- (4 bytes each for single-precision numbers and 8 bytes double-precision).  -->



```{figure} ../../images/c-vs-python-list.png
---
width: 350px
name: c-vs-python-list
alt: c-vs-python-list
align: center
---
Difference between NumPy array (C) and Python lists {cite}`Vanderplas_2022`
```

In short, NumPy's primary data structure is the ndarray (N-dimensional array), which is a **homogeneous**, **multidimensional** array of fixed-size items. This means all elements within an ndarray must be of the same data type (note: To store heterogeneous data, NumPy uses structured arrays). While Python defines only one type of a particular data class (there is only one integer type, one floating-point type, etc.), there are 24 new fundamental Python types to describe different types of scalars in NumPy. 


```{figure} ../../images/np-array-data-types.png
---
width: 400px
name: np-array-data-types
alt: np-array-data-types
align: center
---
Hierarchy of type objects representing the array data types ([Numpy Scalars](https://docs.scipy.org/doc/numpy-1.14.1/reference/arrays.scalars.html))
```

Within the context of NumPy, the terms scalar, vector, and matrix refer to specific dimensions of these arrays.

```{figure} ../../images/scalar-vector-matrix-tensor.png
---
width: 400px
name: scalar-vector-matrix-tensor
alt: scalar-vector-matrix-tensor
align: center
---
Scalar, Vector, Mmatrix, and Tensor ([Harshit Tyagi](https://medium.com/data-science/introduction-to-vectors-and-matrices-using-python-for-data-science-e836e014eb12))
```



<!-- <img src="../images/c-vs-python-list.png"
alt="c-vs-python-list"
style = "width: 350px"> 
name= "c-vs-python-list"
caption = Difference between C and Python lists {cite}`Vanderplas_2022`
-->

## Installing NumPy

To install NumPy, you would:
1. go to command line
2. navigate to your project directory (dsm)
3. activate the virtual environment
4. issue the `pip install` [package] syntax: 

```python
pip install numpy
```
<!-- <code>
pip install numpy
</code> -->

You should see the installation happens like:

```python
(.venv) tychen✪macː~/workspace/dsm$ pip install numpy
Collecting numpy
Downloading numpy-2.3.3-cp312-cp312-macosx_14_0_arm64.whl.metadata (62 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.1/62.1 kB 1.3 MB/s eta 0:00:00
Downloading numpy-2.3.3-cp312-cp312-macosx_14_0_arm64.whl (5.1 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.1/5.1 MB 4.1 MB/s eta 0:00:00
Installing collected packages: numpy
Successfully installed numpy-2.3.3
```


```{note}
Alternatively, in a Jupyter notebook, you may issue `%pip install` [package] in a code cell to install packages just like like `pip install` [package] in the command line. You will also see people use `!pip install` as well. `!pip` runs pip as a shell command, while `%pip` is a Jupyter magic function that works in the current running notebook kernel, which allows you to customize your notebooks. 

Don't forget to comment out your `pip` commands in the cells, or it will keep running every time you run the cells.
```

## Using NumPy

Once you've installed NumPy you can import it as a library:

In [ ]:
import numpy as np

Numpy has many built-in functions and capabilities. For example:
```
arr = np.array([1, 2, 3, 4, 5])     ### creating array
print(np.mean(arr))                 # mean
print(np.std(arr))                  # standard deviation

```

Here we will focus on some of the most important aspects of Numpy: 
- vectors
- arrays
- matrices 
- number generation. 

## Creating NumPy Arrays

### From a Python List/Tuple

You can create an array by directly **casting** a list to an array. Let us create a list first:

In [2]:
nums_list = [1,2,3, 4, 5]
nums_list

[1, 2, 3, 4, 5]

In [3]:
type(nums_list)

list

Now let's cast the list into a numpy array using numpy's `array()` method to create a **1-D** array.

In [4]:
### before using numpy, import
### we usually import packages in the very beginning of a notebook

import numpy as np

In [5]:
arr = np.array(nums_list)       ### casting a list to a numpy array
arr

### now you will see a numpy array, which is array([ ele, ele, ele ]) from the list [1, 2, 3, 4, 5]

array([1, 2, 3, 4, 5])

In [5]:
### data type is different from list too: numpy.ndarray 

type(arr)                   

numpy.ndarray

We can also place the Python list directly into the np.array function to create a NumPy array (note that this is a **2-D** array):

In [6]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


An example of Python **3-D** "array" (list of lists): 

In [7]:
list_of_list = [
    [
        [1, 2, 3, 4], 
        [2, 2, 3, 4], 
        [3, 2, 3, 4]
    ], 
    [
        [4, 2, 3, 4], 
        [5, 2, 3, 4], 
        [6, 2, 3, 4]
    ]
]
list_of_list

[[[1, 2, 3, 4], [2, 2, 3, 4], [3, 2, 3, 4]],
 [[4, 2, 3, 4], [5, 2, 3, 4], [6, 2, 3, 4]]]

Compare the result of evaluation of the Python list above with the NumPy array from the list:

In [8]:
np.array(list_of_list)

array([[[1, 2, 3, 4],
        [2, 2, 3, 4],
        [3, 2, 3, 4]],

       [[4, 2, 3, 4],
        [5, 2, 3, 4],
        [6, 2, 3, 4]]])

#### Using List Comprehension

Note the syntax of list comprehension is an alternative to for loops. Instead of initializing an empty list variable, running the for loop to append the elements, list comprehension is more concise. 

In [9]:
import numpy as np
np.array([i**2 for i in range(10)])

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

### Using arange() Function

**`numpy.arange()`** is a NumPy function used to create arrays with evenly spaced values with a specified interval. It is similar to Python's built-in `range()` function, but returns a NumPy `ndarray` instead of a `range` object, which is more efficient for numerical operations.


In [10]:
np.arange(5)

array([0, 1, 2, 3, 4])

Using the range parameters: start, stop exclusive, stop:

In [11]:
np.arange(2, 11, 2)

array([ 2,  4,  6,  8, 10])

### Using Functions: 

#### zeros(), ones(), and full()

These functions initialize arrays of a specified **shape** filled with zeros, ones, or a constant value, respectively. The syntax for numpy.ones(), zeros(), and full() functions is:

<code>numpy.ones(shape, dtype=None, order='C', *, like=None)</code>

Note that we pass the shape argument using a list or a tuple or list. 

In [4]:
np.ones(3)

array([1., 1., 1.])

In [5]:
np.ones([2,3], int)     ### dtype is int

array([[1, 1, 1],
       [1, 1, 1]])

In [10]:
np.zeros(5, dtype=int)

array([0, 0, 0, 0, 0])

In [11]:
np.zeros((5, 5))        ### by default dtype is float

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
np.full( (5) , 5)

array([5, 5, 5, 5, 5])

In [15]:
np.full((2, 3), 5)      ### fill the shape (2x3) with 5

array([[5, 5, 5],
       [5, 5, 5]])

#### linspace()

linspace( ) stands for linear space. linspace returns evenly spaced numbers over a specified interval. Note that the **stop** parameter is **inclusive**. 

In [17]:
### 11 numbers between 0 and 11, including 10

np.linspace(0, 10, 11, dtype=int)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
arr = np.linspace(0, 26, 27)
print(arr)
print("shape    :", arr.shape)
print("dimension: ", arr.ndim)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 21. 22. 23. 24. 25. 26.]
shape    : (27,)
dimension:  1


In [31]:
arr.reshape(3, 9)

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12., 13., 14., 15., 16., 17.],
       [18., 19., 20., 21., 22., 23., 24., 25., 26.]])

### eye()
Creates an identity matrix

In [18]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Using the numpy.random module 

(These functions are considered "[legacy random generation](https://numpy.org/doc/stable/reference/random/legacy.html#legacy)" and are for simple random data. 

The numpy.random module in NumPy provides tools for generating pseudo-random numbers and sampling from various probability distributions. Some functions in the numpy.random module are commonly used:
- **np.random.rand()**: returns random floating-point numbers (uniform distribution over the interval [0, 1))
- np.random.randn(): returns random floating-point numbers ("standard normal" distribution with mean of 0 and standard deviation of 1)
- **np.random.randint()**: returns random integers from a specified range
- **np.rand
- (note that np.random.random is the same as random.rand(), except random.random() takes the shape argument as a single tuple; e.g., see [stackoverflow](https://stackoverflow.com/questions/47231852/np-random-rand-vs-np-random-random))

In [41]:
### rand: one number

np.random.rand()

0.31519683799947196

In [42]:
### rand: 1D array

from numpy import random     ### different import syntax

random.rand(3)

array([0.48277755, 0.42528074, 0.55715773])

In [43]:
### rand: 2D

random.rand(2, 3)

array([[0.20279338, 0.96122264, 0.84863574],
       [0.10173558, 0.22654765, 0.80718798]])

In [106]:
### randint: 1 number

print(random.randint(10))   ### range between 0 and 10 exclusive
print(random.randint(5, 10))   ### range between 5 and 10 exclusive

6
6


In [164]:
### randin: 1D array (with size parameter)

random.randint( 0, 10 )   ### 0 to 10 exclusie

9

In [187]:
### the choice function

random.choice([3, 5, 7, 9], size = 2)


array([9, 7])

In [204]:
### the size parameter to generate N-D arrays

random.choice([3, 5, 7, 9], size=(3, 5))


array([[3, 7, 9, 7, 7],
       [3, 9, 7, 9, 9],
       [5, 5, 5, 3, 7]])

## NumPy Indexing and Selection

Just like Python lists, square brackets [] are used for selecting the elements or groups of elements from an array:
1. accessing individual elements of a list (**indexing**).
2. selecting sub-sequences (**slicing** with parameters: start, stop exclusive, and step). Note that slicing returns a numpy array.
3. **negative** indexing: begins with -1 from the end of the sequence.

In [22]:
import numpy as np

In [23]:
### creating sample array
arr = np.arange(0,10)

In [24]:
### show the array
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
### indexing 
arr[1]

np.int64(1)

In [26]:
arr[0:3]

array([0, 1, 2])

In [27]:
arr[0:5:2]

array([0, 2, 4])

In [28]:
arr[-1]

np.int64(9)

In [29]:
### start is -3, and stop is -1 exclusive
arr[-3:-1]

array([7, 8])

### Indexing/Slicing 2-D Aarrays (Matrices)

To access a 2-D array (matrices), use the syntax `array[row_index, column_index]`. The general format is **arr[row][col]** or **arr[row, col]**. 

In [30]:
### creating a 2-d array

arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [31]:
### 0-based indexing; 1st row
arr_2d[0]

array([ 5, 10, 15])

In [32]:
### 0-based indexing
arr_2d[1, 2]

np.int64(30)

In [33]:
### 2D array slicing
### shape (2,2) from top right corner

arr_2d[:2, 1:]

array([[10, 15],
       [25, 30]])

#### One More Example: 2-D Array (Matrices)

In [34]:

arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

#Show
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [35]:
### indexing row
arr_2d[1]

array([20, 25, 30])

In [36]:
### Format is arr_2d[row][col] or arr_2d[row,col]

### Getting individual element value
arr_2d[1][0]

np.int64(20)

In [37]:
### getting individual element value
arr_2d[1,0]

np.int64(20)

In [38]:
# 2D array slicing

### shape (2,2) from top right corner
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [39]:
### shape bottom row
arr_2d[2]

array([35, 40, 45])

In [40]:
### also shape bottom row with colon
arr_2d[2,:]

array([35, 40, 45])

## NumPy Array Attributes

### dtype

You can get the data type of the object in the array:

In [209]:
arr = np.arange(25)
arr.dtype

dtype('int64')

In [211]:
arr_string = np.array(['apple', 'banana', 'cherry'])

print(arr_string.dtype)
### U means UTF8, 6 is the longest string

<U6


In [212]:
arr = np.array([1, 2, 3, 4], dtype='i4')

print(arr)
print(arr.dtype)

[1 2 3 4]
int32


### ndim
The ndim attribute represents the number of dimensions (or axes) of the array.

In [220]:
arr.ndim

1

In [221]:
arr_25 = np.arange(25)
arr_55 = arr_25.reshape(5, 5)
arr_55.ndim

2

### shape

The shape attribute **returns a tuple** of integers at every index tells about the number of elements the corresponding dimension has.

In [224]:
arr_2d = np.array([ [1, 2, 3], [4, 5, 6] ])
arr_2d.shape

(2, 3)

In [228]:
### create a 1-D array

arr_vec = np.arange(1, 10, 2)
arr_vec

array([1, 3, 5, 7, 9])

In [229]:
### a vector (an ordered list or an array of numbers, often 
### representing multiple related variables or observations)
arr_vec.shape

(5,)

In [231]:
### np.array([list comprehension])
arr_25 = np.array([ num for num in range(25)])
arr_25

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [46]:
arr_25.shape

(25,)

### The reshape() Function 
The reshape() function changes the shape of a NumPy array without altering its underlying data. It **returns a new array** (or a view of the original array if possible) with the specified new shape.

In [233]:
### arr
arr = np.array(
    [num for num in range(16)]
)

arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [234]:
### reshape
arr = arr.reshape(4, 4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [235]:
arr.reshape(2, 8)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [244]:
### this will not work

# arr.reshape(5,5)

In [98]:
arr_25 = np.arange(25)
arr_25.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [99]:
arr_25.reshape(5, 5).shape

(5, 5)

In [245]:
### reshape does not change the object

arr_25

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [246]:
arr_25.shape

(25,)