# Numpy: Getting Started

- pip install numpy
- import numpy
- NumPy is usually imported under the np alias: import numpy as np
- check version
- To create an ndarray, we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray


## Create ndarray objects

NumPy is used to work with arrays. The array object in NumPy is called ndarray.

We can create a NumPy ndarray object by using the array() function.

In [ ]:
## 



In [1]:
import numpy as np

In [2]:
##### check version

print(np.__version__)

2.1.3


## Check VENV

- make sure you create a venv for jupyter notebook

In [3]:
!jupyter kernelspec list

Available kernels:
  python3    /Users/tychen/.venv_common/share/jupyter/kernels/python3


In [5]:
# !jupyter kernelspec remove venv

In [6]:
arr = np.array([1, 2, 3])

In [20]:
##### evaluate an ndarray

arr

array([1, 2, 3, 4, 5])

In [19]:
##### print an ndarray object

print(arr)

[1 2 3 4 5]


In [9]:
print(type(arr))

<class 'numpy.ndarray'>


In [14]:
arr2 = np.array((1, 2, 3))
arr2

##### same thing. arr2 is converted into an ndarray

array([1, 2, 3])

## Dimensions in Arrays

### 0-D Arrays

- 0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array.



In [16]:
arr = np.array(42)
print(arr)

42


### 1-D Arrays

- An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.
- These are the most common and basic arrays.



In [17]:
arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


### 2-D Arrays
- An array that has 1-D arrays as its elements is called a 2-D array.
- These are often used to represent matrix or 2nd order tensors.
- NumPy has a whole sub module dedicated towards matrix operations called numpy.mat

In [21]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


### 3-D arrays

- An array that has 2-D arrays (matrices) as its elements is called 3-D array.
- These are often used to represent a 3rd order tensor.

In [23]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


## Check Number of Dimensions?

- NumPy Arrays provides the ndim attribute that returns an integer that tells us how many dimensions the array have.

In [24]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


## Higher Dimensional Arrays

- An array can have any number of dimensions.
- When the array is created, you can define the number of dimensions by using the ndmin argument.

In [27]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In this array the innermost dimension (5th dim) has 4 elements, the 4th dim has 1 element that is the vector, the 3rd dim has 1 element that is the matrix with the vector, the 2nd dim has 1 element that is 3D array and 1st dim has 1 element that is a 4D array.